### ISSUE TITLE
Support selecting IDs with an alias in require-id-when-available rule

### ISSUE THREAD

**Issue by grubersjoe** [B2o5T/graphql-eslint#1017]
In our code base we sometimes select the `id` of a type with an alias as follows:

```gql
someType {
  id: someOtherUniqueField
}
```

In this case the `require-id-when-available` rule will fail, because `id` is in fact not selected directly. However, using such an alias guarantees that the resolved data will contain an `id` field (if this is an unique key is another question). So I think the rule should also support this pattern.

I have some [code](https://github.com/grubersjoe/graphql-eslint/commit/b9080ec089873d91b6b69b75bc915d235ab5d7c1) that checks if an alias for the configured `id` field exists so that the rule will also pass in this case. Would you be interested in a merge request to add this feature?

**Comment by grubersjoe** [comment]
Okay I've opened a MR here: https://github.com/B2o5T/graphql-eslint/pull/1019

**Comment by B2o5T** [comment]
@grubersjoe available in [`@graphql-eslint/eslint-plugin@3.10.2`](https://github.com/B2o5T/graphql-eslint/releases/tag/%40graphql-eslint%2Feslint-plugin%403.10.2)

Thank you for your first contribution 🎉
