### ISSUE TITLE
3.10.x processor causes eslint to not enforce normal rules in code files

### ISSUE THREAD

**Issue by wheeler** [B2o5T/graphql-eslint#1021]
# Describe the bug

I have a config with the processor being used on code files. When upgrading to `3.10.x` all non-graphql-code lint rules are not being enforced anymore. Downgrading to `3.9.1` restores enforcement of eslint code rules.

**To Reproduce**
- in the eslint config, use the `graphql-eslint` processor config on js files
    ```
    {
      files: ['*.js', '*.jsx', '*.ts', '*.tsx'],
      processor: '@graphql-eslint/graphql',
    },
    ```
- make lint errors in non-gql tags
- run eslint
- no errors output

**Expected behavior**

using `processor: '@graphql-eslint/graphql'` should not disable code linting

**Environment:**

- OS: MacOS 12.3
- `@graphql-eslint/eslint-plugin@3.9.1`:
- NodeJS: v16.13.0

# Additional context

I don't exactly know how the processor works but I suspect this is related to the changes in https://github.com/B2o5T/graphql-eslint/pull/982

### before:

https://github.com/B2o5T/graphql-eslint/blob/75ec7d1dc7801134b4e6cca95c78463f4ed64551/packages/plugin/src/processors/code-files.ts
```
preprocess(text: string, filename: string): (string | Linter.ProcessorFile)[] {
  ...
  if (filename && text && RELEVANT_KEYWORDS.some(keyword => text.includes(keyword))) {
    ...
	blocks.push(text);

	return blocks;
  }

  return [text];
},
```

### after:
https://github.com/B2o5T/graphql-eslint/blob/96ba21a0e8f15e48623416c3b0199f868fe2026c/packages/plugin/src/processor.ts#L14-L17

So this looks like a pretty clear problem here - if the code file does not contain any keywords... before it would give the `[text]` to eslint, now it gives nothing (`[]`) to eslint...

**Comment by B2o5T** [comment]
Hi @wheeler thanks for the report and investigation, you are totally right, preprocess method should always return `code` string, I improved a test for this case for the future.

Fixed in [`@graphql-eslint/eslint-plugin@3.10.2`](https://github.com/B2o5T/graphql-eslint/releases/tag/%40graphql-eslint%2Feslint-plugin%403.10.2)
