### ISSUE TITLE
wrong documentation for eslint.validate

### ISSUE THREAD

**Issue by eng-dibo** [B2o5T/graphql-eslint#1070]
`eslint.validate` is now obselated as of [eslint extension docs](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).

please mention that warning or remove `eslint.validate` from vscode integration section

**Comment by B2o5T** [comment]
Thanks for the hint 👍, updated!

**Comment by dylanwulf** [comment]
Sorry I'm a bit confused. The `eslint.validate` option is obsolete, but it still seems to be necessary in order for this tool to work correctly in vscode? I can lint `.graphql` files in the CLI just fine, but in vscode it won't lint any `.graphql` files unless I specify this option. Is there another option that I'm missing?
