### ISSUE TITLE
alphabetize rule doesn't support nested query objects

### ISSUE THREAD

**Issue by AvronNet** [B2o5T/graphql-eslint#1073]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

When applying role to queries that have nested query objects. 
Error is `Cannot read property '0' of undefined` within a graphql document.
we should be able to apply this rule to complex queries.

**To Reproduce**
Try to lint a query with a nested query object eg.:

```
query {
  root_object {
     a
     b {
        subprop_a
        subprop_b
    }
}
```

**Expected behavior**

Linting analyses alphabetical order within every nested object.

**Environment:**

- OS:
- `@graphql-eslint/eslint-plugin`: 3.10.3
- Node.js: 14.17.4

eslint setup:
```
overrides: [
        {
            files: ['src/graphql/**/*.ts'],
            processor: '@graphql-eslint/graphql',
        },
        {
            files: ['*.graphql'],
            parser: '@graphql-eslint/eslint-plugin',
            plugins: ['@graphql-eslint'],
            rules: {
                '@graphql-eslint/alphabetize': ['error', {
                    fields: [ 'InputObjectTypeDefinition','InterfaceTypeDefinition', 'ObjectTypeDefinition' ],
                    selections: ['FragmentDefinition', 'OperationDefinition'],
                    variables: ['OperationDefinition'],
                    arguments: ['FieldDefinition','Field','DirectiveDefinition','Directive'],
                }]
            },
            parserOptions: {
                operations: './src/graphql/**/*.ts',
                schema: './src/graphql/schema.json',
            },
        },
    ],
```

**Comment by B2o5T** [comment]
Your GraphQL document is invalid, you have a missing `}` bracket at the end, I can't reproduce your error even with a valid document. Consider submitting a PR with the failed test in this file https://github.com/B2o5T/graphql-eslint/blob/master/packages/plugin/tests/alphabetize.spec.ts if you really found a problem with this rule.
