### ISSUE TITLE
JS uncaught error in selection-set-depth's suggestion feature

### ISSUE THREAD

**Issue by tgohn** [B2o5T/graphql-eslint#1090]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

After https://github.com/B2o5T/graphql-eslint/pull/971, for
selection-set-depth rules, if the depth error occured in a different
file than source file (e.g. in an imported fragment file), JavaScript
exception might thrown because it can not find the token node in source
file.

**To Reproduce**
- Failed test code: https://github.com/tgohn/graphql-eslint/commit/686c8fd1bc66bc1fdab99c424c05176f8cd82c83
- In this error, [token](https://github.com/B2o5T/graphql-eslint/blob/0d48603bc0b00bf7872480546f0e10300bf63679/packages/plugin/src/rules/selection-set-depth.ts#L127) is undefined.

Screenshot of jest run:
<img width="1379" alt="Screenshot 2022-06-17 at 5 32 12 PM" src="https://user-images.githubusercontent.com/6629569/174271589-913a4c89-43e8-41a6-b072-e2b53a628e87.png">

**Expected behavior**

ESLint's suggestion feature should not throw errors.

**Environment:**

- OS: MacOs
- `@graphql-eslint/eslint-plugin`: 0d48603bc0b00bf7872480546f0e10300bf63679
- Node.js: v16.14.0

**Additional context**

**Comment by B2o5T** [comment]
fixed in [@graphql-eslint/eslint-plugin@3.10.5](https://github.com/B2o5T/graphql-eslint/releases/tag/%40graphql-eslint%2Feslint-plugin%403.10.5)

Thanks for catch! Now there will be no suggestions for external fragments since we can apply fixes only for the actual file :)
