### ISSUE TITLE
graphql-eslint crashes ESLint

### ISSUE THREAD

**Issue by therealgilles** [B2o5T/graphql-eslint#1092]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**
I am trying to use graphql-eslint with Gatsby and VSCode (and its ESLint and GraphQL extensions). My code files are in TypeScript and contain graphql and gql template strings. I am seeing ESLint crash if a TS file with graphql/gql template strings contain syntax errors.

Here are my observations:
1) ESLint runs graphql-eslint as a processor on the file.
2) graphql-eslint calls @graph-tools/graphql-tag-pluck to extract the templates string.
3) @graph-tools/graphql-tag-pluck in turn calls @babel/parser.
4) @babel/parser (called without errorRecovery) detects the syntax error and throws an error.
5) The error throw propagates up and makes ESLint crash as follows:

```JS
> eslint --ignore-path .gitignore .

Oops! Something went wrong! :(

ESLint: 8.17.0

SyntaxError: Unexpected token, expected "=" (20:8)
    at instantiate (.../node_modules/@babel/parser/lib/index.js:72:32)
    at constructor (.../node_modules/@babel/parser/lib/index.js:358:12)
    at Object.raise (.../node_modules/@babel/parser/lib/index.js:3341:19)
    at Object.unexpected (.../node_modules/@babel/parser/lib/index.js:3379:16)
    at Object.expect (.../node_modules/@babel/parser/lib/index.js:4008:28)
    at .../node_modules/@babel/parser/lib/index.js:9566:12
    at Object.tsInType (.../node_modules/@babel/parser/lib/index.js:9596:14)
    at Object.tsParseTypeAliasDeclaration (.../node_modules/@babel/parser/lib/index.js:9564:32)
    at Object.tsParseDeclaration (.../node_modules/@babel/parser/lib/index.js:9913:23)
    at Object.tsParseExpressionStatement (.../node_modules/@babel/parser/lib/index.js:9880:21)
```

The VSCode ESLint server runs on typing, so just editing a file to make any changes results in an ESLint crash, which appears as a small window on the lower right (which is obstructive and distracting). And really ESLint should not be crashing.

I am a bit surprised to be the only one running into this issue so I wonder if I'm missing something or have some kind of configuration issue. What am I doing wrong?

**To Reproduce**
See above.

**Expected behavior**
I would expect ESLint not to crash and to report the syntax error.
graphql-eslint should probably catch the error thrown by @babel-parser through @graphql-tools/graphql-tag-pluck and bail, i.e. return the original code as is.

**Environment:**
- OS: MacOS Ventura 13.0 Beta -- Darwin x64 22.0.0
- `@graphql-eslint/eslint-plugin`: 3.10.4
- Node.js: v16.15.0
- VSCode Version: 1.69.0-insider

**Comment by therealgilles** [comment]
I made a bit of progress tracking down this issue. ESLint still crashes on the command line but only crashes inside VSCode if I have the following in .vscode/settings.json:

```JSON 
  // I have to comment this out, otherwise ESLint crashes inside VSCode, displaying popup windows one after the other on each crash.
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "graphql"
  ],
```

Now ESLint still crashes when run on the command line, which is certainly the preferable behavior.

**Comment by therealgilles** [comment]
Is there a reason why the preprocess code of the processor is not within a try/catch like below?

```JS
const processor = {
    supportsAutofix: true,
    preprocess(code, filePath) {
      try {
        if (RELEVANT_KEYWORDS.every(keyword => !code.includes(keyword))) {
            return [code];
        }
        const extractedDocuments = graphqlTagPluck.parseCode({
            code,
            filePath,
            options: {
                globalGqlIdentifierName: ['gql', 'graphql'],
                skipIndent: true,
            },
        });
        const blocks = extractedDocuments.map(item => ({
            filename: 'document.graphql',
            text: item.content,
            lineOffset: item.loc.start.line - 1,
            offset: item.start + 1,
        }));
        blocksMap.set(filePath, blocks);
        return [...blocks, code /* source code must be provided and be last */];
      } catch (err) { // Not sure what to do with the reported error
        return [code];
      }
    },
```

**Comment by B2o5T** [comment]
closing since this will be fixed in ESLint directly
