### ISSUE TITLE
Associate a tag name to a particular project in the GraphQL config?

### ISSUE THREAD

**Issue by therealgilles** [B2o5T/graphql-eslint#1094]
**Is your feature request related to a problem? Please describe.**
I'm using GraphQL on Gatsby with the gatsby-source-wordpress plugin and WP-GraphQL. Gatsby generates and uses its own schema during its build process, while WP-GraphQL creates a different schema on the WordPress instance.

The Gatsby Graphql commands use the graphql template string, whereas the commands sent to WP-GraphQL through the Apollo client use the gql template string.

Wondering if it would be best to associate each schema with the corresponding template string. Maybe this is not useful?

**Describe the solution you'd like**
One possible solution would be to have a way to associate a tag name to a particular project in the GraphQL config, or do it at the eslint rule level. The apollographql/eslint-plugin-graphql has a tagName option when specifying its graphql/template-strings rule.

**Comment by therealgilles** [comment]
Hi @B2o5T, I thought I had described the use case above. In short, I use the `graphql` tag for Gatsby GraphQL requests (schema 1) and the `gql` for Apollo GraphQL requests (schema 2). It would be great to be able to associate a tag with specific graphql-eslint rules and a specific `project` in graphql-config.js, but maybe it's not a must.

**Comment by B2o5T** [comment]
For applying specific rules on specific files you can use overrides sections in eslint config. Take a look of config in monotepo example https://github.com/B2o5T/graphql-eslint/blob/master/examples/monorepo/.eslintrc.cjs

**Comment by B2o5T** [comment]
I guess with this example you can achieve it https://github.com/B2o5T/graphql-eslint/tree/master/examples/multiple-projects-graphql-config

**Comment by therealgilles** [comment]
@B2o5T Thank you for the detailed example, really appreciated! I had worked around the problem by using `*.graphql` files for Apollo queries/mutations, and inline `graphql`-tag queries for Gatsby. I'll give it a go.
