### ISSUE TITLE
no-unreachable-types: Support document-only fragments

### ISSUE THREAD

**Issue by besfahbod** [B2o5T/graphql-eslint#1106]
**Is your feature request related to a problem? Please describe.**

It's common to have document-only `directive`s in schemas. Such schema items are, by definition, "unreachable".

Example:
```
directive @onLoggedIn on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
```

The [no-unreachable-types](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/no-unreachable-types.md) rule, however, does not understand this, and detects them as issues.

Of course, it's possible to disable the lint rule for such items; however, that would be redundant to the item definition.

**Describe the solution you'd like**
**Describe alternatives you've considered**

I guess there are different ways to handle this:

1) Make `no-unreachable-types` smarter, without new options for users to do so.

2) Add options to `no-unreachable-types` to allow control over item types, so a user can disable this check specifically on `directive`s.

3) Add options to `no-unreachable-types` to allow user to disable the check depending on the allowed location of directives.

From these, I think (2) is the easiest to implement and a useful generic control for the rule. The other two are more complicated. Solution (1) could be ideal, while solution (3) could be hard-to-configure.

**Comment by B2o5T** [comment]
Hi @besfahbod thanks for your report. You are right, this rule should ignore all operations (request) directives.
<img width="538" alt="image" src="https://user-images.githubusercontent.com/7361780/177535233-4f91ce2a-6ed0-434d-8d2b-807eeeb58907.png">

This will be fixed, you can use `eslint-disable` comments temporarily
