### ISSUE TITLE
Fragments are not validated against `@graphql-eslint/require-id-when-available`

### ISSUE THREAD

**Issue by benatshippabo** [B2o5T/graphql-eslint#1117]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Fragments are not validated against `@graphql-eslint/require-id-when-available` rule.

#### Schema
```gql
type Query {
  user(id: String!): UserResult
}

union UserResult = Account | Error

type Account {
  id: ID!
  name: String!
  phone: String
}

type Error {
  message: String!
}
```

#### Query

```gql
query UserById($id: String!) {
  user(id: $id) {
    ... on Account {
      # inline fragment: we expect an error here about a missing `id` field
      ...UserFields
    }

    ... on Error {
      message
    }
  }
}

fragment UserFields on Account {
  # fragment: we expect an error here about a missing `id` field
  name
  phone
}
```

**To Reproduce**

https://github.com/benatshippabo/graphql-eslint-bug

**Expected behavior**

We expect eslint to error on the inline `Account` fragment and the `Account` fragment.

**Environment:**

- OS: MacOS 12.4
- `@graphql-eslint/eslint-plugin`: ^3.10.6
- Node.js: v16.16.0

**Additional context**

**Comment by benatshippabo** [comment]
@TuvalSimha @B2o5T any updates on this? It seemed like the solution was already written https://github.com/B2o5T/graphql-eslint/pull/1118#issuecomment-1199122972

**Comment by B2o5T** [comment]
PR always welcome

**Comment by B2o5T** [comment]
@benatshippabo try 3.16.1-alpha-20230226183026-b86ac84

**Comment by benatshippabo** [comment]
It works now thank you!
