### ISSUE TITLE
Apollo Federation Support?

### ISSUE THREAD

**Issue by dchambers** [B2o5T/graphql-eslint#1123]
## Problem

Hi 👋. Unless I'm overlooking something, `graphql-eslint` does not appear to support the linting of Apollo Federation GraphQL schemas. For example, the following is a valid federated schema:

```gql
extend type Product @key(fields: "id") {
    id: ID! @external
    inStock: Boolean!
}
```

Yet linting this schema yields this response:

```
Error: Error while loading rule '@graphql-eslint/no-unreachable-types': Error while loading schema: Cannot extend type "Product" because it is not defined.

Unknown directive "@key".

Unknown directive "@external".
```

This is because:

1. The federated machinery types that will be automatically added by the subgraph are not present in the source schema.
2. Apollo Federation is using the `extend` keyword as a means of extending a type that is defined remotely.

## Potential Solutions

Is there some cunning trick I should be aware of that would allow me to get linting feedback within VSCode despite these issues?

Right now all I can think of is:

1. Manually define the machinery types in the source schema.
   - Assuming it would even work this seems really dodgy, particularly since some machinery types (e.g. `_Entity`) are calculated dynamically.
2. Migrate all of our subgraphs to v2, where the `extend` keyword has been dropped.
   - We've been undergoing this migration for a while, and it's far from trivial, so is unfortunately not a journey we're likely to conclude any time soon.

Alternatively, would you be open to me submitting a PR where I?:

1. Automatically detected schemas that were using Apollo Federation.
2. Dynamically created the machinery types the schema might depend on.
3. Dynamically created stub types for any types that the schema extends.

**Comment by B2o5T** [comment]
Hi @dchambers 👋 graphql-eslint expect to receive full schema. You can manually extend your schema in your eslint config, see my comment https://github.com/B2o5T/graphql-eslint/discussions/1063#discussioncomment-2721160

**Comment by dchambers** [comment]
Thanks for the very speedy response @B2o5T! I actually did use the technique of using `parserOptions.schema` as a way of introducing the federation machinery types previously, but still hit the issue that we'd need to manually create stub types too. Given that the need for these will go away with Federation v2 I'm probably happy to hand edit these stub types until subgraphs switch over to Fed v2.

Will close this ticket for now.
