### ISSUE TITLE
Operations inside graphql`` statements are not being linted

### ISSUE THREAD

**Issue by BrianBusby** [B2o5T/graphql-eslint#1133]
Not sure if this is a bug or just a feature: I have .graphql schema files being properly linted, but we use relay and our operations are defined inside `graphql` statements rather than `gql` and it seems the linter isn't finding them. I was sure to add the following  as an override per the instructions:

```
  {
    files: ['*.tsx', '*.ts'],
    processor: '@graphql-eslint/graphql',
  },
```

**Comment by B2o5T** [comment]
Hi, can you share your eslint config?

**Comment by BrianBusby** [comment]
We have a very large eslint config but I can give you an example of what I'm seeing:

the linting config I added around graphql operations are as follows:

```
  {
    files: ['Product'.tsx],
    processor: '@graphql-eslint/graphql',
  },
  {
    files: ['*.graphql'],
    extends: 'plugin:@graphql-eslint/operations-recommended',
  },
```
when I run lint I get no issues, although I've put a few issues into the listed file:

```
  const data = useLazyLoadQuery<Product>(
    graphql`
      query ($type: Permission!, $category: Category!, $test: string) {
        permissions(type: $type, category: $category, category: $category) {
          test
          test
        }
      }
    `,
    { type: permissionType, category: permissionCategory },
  );
```

the above operation has duplicate variable names, duplicate fields, and an anonymous operation.

If I change my eslint config to:

```
  {
    files: ['Product.tsx'],
    processor: '@graphql-eslint/graphql',
    extends: 'plugin:@graphql-eslint/operations-recommended',
  },
  {
    files: ['*.graphql'],
    extends: 'plugin:@graphql-eslint/operations-recommended',
  },
```

then I get a linting error in that file:
`1:0  error  Parsing error: [graphql-eslint] Syntax Error: Unexpected Name "import"`

so I know that graphql-eslint can find the file and lint it. It just doesn't seem able to lint the actual operations.

**Comment by B2o5T** [comment]
Take a look of this example with code files https://github.com/B2o5T/graphql-eslint/blob/master/examples/code-file/.eslintrc.cjs
You have an incorrect eslint configuration, split it to overrides sections

**Comment by B2o5T** [comment]
Also remove first `extends` from Product.tsx file, you don't need to run graphql-eslint rules on code files only on graphql files

**Comment by BrianBusby** [comment]
I should have been more clear; my lint config currently looks like this:

```
{
  overrides: [
      {
          files: ['Product.tsx'],
          processor: '@graphql-eslint/graphql',
      },
      {
        files: ['*.graphql'],
        extends: 'plugin:@graphql-eslint/operations-recommended',
      },
  ]
}
```

this produces no linting errors even though there are errors in the graphql operations inside the listed file.

**Comment by B2o5T** [comment]
Can you add simple reproduction repo? It will be simple to help you

**Comment by Dodie324** [comment]
Having similar issues as @BrianBusby. I'm trying to migrate from `eslint-plugin-graphql`, but not sure this package is actually validating my queries/mutations written inside a `.ts` file.

Here is my config setup:

```overrides: [
    {
      files: ['*.ts'],
      processor: '@graphql-eslint/graphql',
    },
    {
      files: ['*.graphql'],
      parser: '@graphql-eslint/eslint-plugin',
      plugins: ['@graphql-eslint'],
      rules: {
        '@graphql-eslint/no-duplicate-fields': 'error',
        '@graphql-eslint/no-deprecated': 'error',
      },
    },
  ],
  ```

**Comment by B2o5T** [comment]
@Dodie324 Sorry but without reproduction repo I’m unable to help, your configuration seems to be valid and it follows configuration from examples

**Comment by BrianBusby** [comment]
@B2o5T I was able to fix the issue on my end; we initialize ESLint at a point in our front end linting workflow and .graphql needed to be added to the `extensions` property array. Thanks for trying to help.

**Comment by Dodie324** [comment]
@BrianBusby Can you share what your extensions array looks like now?

**Comment by Dodie324** [comment]
Or can anyone else shed some light into what Brian is referring to by adding to the `extensions` property array?

**Comment by ammoradi** [comment]
@Dodie324 I had the same issue with the following eslint configuration file and lint command:
`.eslintrc.js`:
```js
module.exports = {
  // root level parser, extends, plugins, ... for the typescript eslint configurations
  overrides: [
    {
      files: ['*.ts'],
      processor: '@graphql-eslint/graphql',
    },
    {
      files: ['*.graphql'],
      parser: '@graphql-eslint/eslint-plugin',
      plugins: ['@graphql-eslint'],
      parserOptions: {
        'schema': './schema.graphql'
      },
      rules: {
        '@graphql-eslint/no-deprecated': 'error'
      }
    },
  ]
}
```
`lint` command:
```bash
eslint --ext ts,js,tsx,jsx src/
```


There were two problems:
1. we should avoid defining any top-level configurations as mentioned here [https://github.com/B2o5T/graphql-eslint/blob/master/examples/code-file/.eslintrc.cjs](https://github.com/B2o5T/graphql-eslint/blob/master/examples/code-file/.eslintrc.cjs). So, the new `.eslintrc.js` is:
```js
module.exports = {
  overrides: [
    {
      files: '*.[jt]s?(x)',
      // former root level parser, extends, plugins, ... for the typescript eslint configurations
    }
    {
      files: ['*.ts'],
      processor: '@graphql-eslint/graphql',
    },
    {
      files: ['*.graphql'],
      parser: '@graphql-eslint/eslint-plugin',
      plugins: ['@graphql-eslint'],
      parserOptions: {
        'schema': './schema.graphql'
      },
      rules: {
        '@graphql-eslint/no-deprecated': 'error'
      }
    },
  ]
}
```
2. add `.graphql` extension to the `--ext` of the lint command (I think @BrianBusby meant this!). However, we could completely eliminate the extensions with the new configuration, so the new lint command would be: `eslint src/`.

I hope it helps you!

**Comment by Dodie324** [comment]
Thanks for looking into this @ammoradi . Adding that sample you linked would definitely be useful. Surprised it's not mentioned in the README cc @B2o5T

**Comment by ardatan** [comment]
@ammoradi Would you contribute to the docs with a PR?

**Comment by onsah** [comment]
Can we document this in `README`? I wasted 2 hours to find this issue and fix the same problem.
