### ISSUE TITLE
Enforce `@oneOf` output types for mutation fields

### ISSUE THREAD

**Issue by dotansimha** [B2o5T/graphql-eslint#1137]
We recently started using the following pattern for writing mutations:

```graphql
type Mutation {
  doSomething: DoSomethingMutationResult!
}

interface Error {
  message: String!
}

type DoSomethingMutationResult @oneOf {
  ok: DoSomethingSuccess
  error: Error
}

type DoSomethingSuccess {
  # ...
}
```

This helps with the following:
* It's easier to communicate user errors in the response
* Errors can contain any additional info the client might need (error code, validation info and so on) 
* Reduce the need to use `... on Error` and so on -  no need to specify `type` names in the query

**Comment by B2o5T** [comment]
Rule name? `require-one-of-mutation-result-type-pattern` ?

**Comment by B2o5T** [comment]
Or `require-mutation-result-type-pattern-with-oneof`
