### ISSUE TITLE
Type error in `RuleDocsInfo`

### ISSUE THREAD

**Issue by Berger92** [B2o5T/graphql-eslint#1146]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Hi 👋 
This is just a small thing that I discovered when I wanted to add urls to our rules and TS didn't like it with the `strict` flag on, because `url` wasn't part of `RuleDocsInfo`.

I took a closer look and discovered that the problem is caused by `docs` being optional, and therefore the type returned by `Omit<Rule.RuleMetaData['docs'], 'category'>` is `{}`.

```
export type RuleDocsInfo<T> = {
  docs: Omit<Rule.RuleMetaData['docs'], 'category'> & {   <<<<<
    category: CategoryType | CategoryType[];
    requiresSchema?: true;
    requiresSiblings?: true;
    ...
  };
};
```

**To Reproduce**

![Screenshot 2022-08-25 at 10 30 03](https://user-images.githubusercontent.com/8849858/186630865-42a15023-ad5b-4dc4-91f9-f5438a4ab45a.png)

**Expected behavior**

I think you wanted to keep all the properties from `docs` except for `category`, so that should be happening.

**Proposed solution**

[Adding](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEoFcA2ECyExwAicByA3gFDLXIAmA9ggM4D8AXOVTdwPQBUfZAAco9AG7BaEJsjAALFEzn0oYOtIRRgQsMHohk9GLIXIoWFKBMoA2uewzQUgB4BdABRywYIUzY8eaUxQMAA6FQBzHgZmHntpHgBKZD4eLm5qKSZNbV19dmQmMC0QCOQAH2R0ECkYUAhaAG50jP5BJiEIBGA66WtkBThaUDLqqShkAHc5YAQ5fvjkYBlgooalg3lbeMcaiDdPb19-QKZg8HCoKJimOItb5NSW7gQSCAiVAE8CopKyyrGEDqIAazQyNDaSxk03wCgmW2QAAMAET7SA1JjIjios4hNhQLr0AC2RIge1oyMRwlEnVUnw2yDgyBsCH0dQi6CgJD0Bjq2A8Xh8fgCQRCl2ujFu6CY0AAtBzJBAeKyQOzOSMAMRosnDUqylVqrl5ECyvnSZJkuAAIwcCwsKTS4OoBNZJJ1DQKVvo9GwcAMAL2wNBzwhAkKnW6vRkCIAqqgADKMtTTWbzBEwLCYOiMdCk8Dc-TIV4GK0oRBIJgy2gOkPUTmYH7FEYVKqB+pNWvISEdLo9YB9GFbCY7It+sz4TkGJjoCIRaTGmTuWpwLBgaP0ZDwTAypbGYnAbwNR6Op3T2fznme72+-2t2rtsE0AC+LVJlbgc9YHDIzLfTA-EAAJK0BwvwjK4oFNqUyBPi2gJBh23B1M41rYAUyKslIyItsiKaQB0iAQNhAb3iCiE0HIcBMAAyjOn4LlePoQGOJFAg+FAvhQYCfJ0yAAHIQJMAAqPEoAAvMgADyRIHgAPKgEAAI7oMABK0PJFh4AQxAEAAfDYADkNwGa4AA0yAGa8kAfFAnwGbpQA) `Required` solves it. 

![Screenshot 2022-08-25 at 10 39 43](https://user-images.githubusercontent.com/8849858/186631621-21d329a6-5b99-4ad2-9005-f3141023e37d.png)

**Environment:**

- OS: MacOS Monterey
- `@graphql-eslint/eslint-plugin`: 3.10.7
- Node.js: 16

**Comment by Berger92** [comment]
Hey @B2o5T 👋  
Any thought on this? 🙂

**Comment by B2o5T** [comment]
Hi @Berger92 sorry for delay ! Will be fixed on next release!

**Comment by Berger92** [comment]
Hi @B2o5T, no worries. Thanks for taking a look. If you like the proposed solution I'm happy to put the PR together.

**Comment by B2o5T** [comment]
Hi @Berger92 👋 and sorry for the long time fixing this issue (was too busy with another open source project 😄), I don't think `Required<RuleMetaData['docs']>` is the right way as:
1. it's requires always set `recommended` to `true`/`false` (setting `false` for me it's redundant)
2. it's requires always set `suggestions` field to `true`/`false`, but this field is marked as deprecated and should be omitted

Anyway I enhanced `RuleDocsInfo` type to always requires `description` and `url` fields

You can already test these changes and give your feedback with alpha version `3.11.0-alpha-20220923193910-c1bb619` that will be included in the next release 🚀

**Comment by Berger92** [comment]
@B2o5T Thanks for getting back to me. My proposal was based on not modifying the types, but I like your approach. However, I **disagree** with making `description` and `url` required. That's not the case [in eslint](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0c0777bd1dd9b34f4fa4e36aecfdc3228e64d454/types/eslint/index.d.ts#L554-L565).

**Comment by B2o5T** [comment]
@Berger92 made `description` and `url` optional as well as `meta.docs`

Try `3.11.1-alpha-20220926112156-14d4be3`

**Comment by Berger92** [comment]
Yeah, good idea Re `meta.docs` 👍 I'll take a look a bit later today.

**Comment by Berger92** [comment]
Hi @B2o5T I've taken a look and whilst it doesn't bother my use case, there's something off with it again. It doesn't seem to like the `description` field. Although, this time, I don't know why 🤔 
```
 error TS2322: Type '{ category: "Schema"; description: string; url: string; }' is not assignable to type 'RuleDocsInfo<any[]>'.
  Object literal may only specify known properties, and 'description' does not exist in type 'RuleDocsInfo<any[]>'.

14             description: 'Enforces usage of `@contact` directive on the schema.',
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  ../../node_modules/@graphql-eslint/eslint-plugin/types.d.ts:68:9
    68         docs?: RuleDocsInfo<Options>;
               ~~~~
    The expected type comes from property 'docs' which is declared here on type 'Omit<RuleMetaData, "docs"> & { docs?: RuleDocsInfo<any[]> | undefined; }'



```

**Comment by Berger92** [comment]
Actually, having dug deeper, it looks like the same problem as reported in the first comment in this issue: `Omit` and optional field result in an interesting type.
So, you can use the `Required` utility type (notice that it won't change any of the fields inside, it just helps us get the correct type for the Omit)
```
export declare type RuleDocsInfo<T> = Omit<Required<Rule.RuleMetaData>['docs'], 'category' | 'suggestion'> & { ... }
```
or  just manually declare the fields:
```
export declare type RuleDocsInfo<T> = Omit<Rule.RuleMetaData['docs'], 'category' | 'suggestion'> & {
    description?: string | undefined;
    recommended?: boolean | undefined;
    url?: string | undefined;
    
    category: CategoryType | CategoryType[];
    ...
}
```

**Comment by B2o5T** [comment]
Hey @Berger92 can you make a PR with your change? :)

**Comment by Berger92** [comment]
Sure, I'll crack on with it today.

**Comment by B2o5T** [comment]
Hi @Berger92, I decided to not fixing this issue, since it’s issue on your side and maybe due your typescript version.

I already applied your suggestions for fields to mark them as optional, for me this issue is done and completed. Sorry

**Comment by Berger92** [comment]
Hi @B2o5T , the issue isn't the typescript version (I am also on 4.7.4). As I said it in the first comment ☝️ , it is the `strict` flag in typescript options. I know it is an optional flag, but it does point out the type issue with `RuleDocsInfo`. If you turn on strict mode for this project, you'll see exactly the same error:

![image](https://user-images.githubusercontent.com/8849858/192514686-026922dd-bc5f-4634-8509-c52cf15ff974.png)

Here's my [tiny PR](https://github.com/B2o5T/graphql-eslint/pull/1176) to fix it. If you don't like it, that's fine, I can have a workaround for it locally 🙂
