### ISSUE TITLE
Apply graphql-tag-pluck config options

### ISSUE THREAD

**Issue by JimmyPaolini** [B2o5T/graphql-eslint#1155]
**Is your feature request related to a problem? Please describe.**

I'm facing a problem that I can't lint my graphql queries because I'm using custom graphql-tag-pluck tag names that cannot be configured in graphql-eslint, so I think graphql-eslint should allow users to configure its graphql-tag-pluck options. I'm working on a project with multiple schemas with corresponding custom gql tags, and I'd like to use graphql-eslint to lint my queries in these custom tags. 

For example, a query to the schema "foo" looks like ``const fooQuery = foo`query FooItems {...}` ``, and a query to schema "bar" looks like ``const barQuery = bar`query BarItems {...}` ``, and graphql-eslint cannot lint these queries because they don't use the tags `gql` or `graphql` or the magic comment `/* GraphQL */` as defined in the source code [here](https://github.com/B2o5T/graphql-eslint/blob/master/packages/plugin/src/processor.ts#L9) and  [here](https://github.com/B2o5T/graphql-eslint/blob/master/packages/plugin/src/processor.ts#L22) .

**Describe the solution you'd like**

Since graphql-config is already being used, it can be extended to include options for graphql-tag-pluck, then those options applied to the existing config as follows in `processor.ts`:
```
import graphqlConfig from 'graphql-config';
...
const graphqlTagPluckOptions = graphqlConfig.loadConfigSync({}).getDefault().extensions.graphqlTagPluck
const graphqlTags = graphqlTagPluckOptions.modules.map(({identifier}) => identifier)
const RELEVANT_KEYWORDS = ['gql', 'graphql', '/* GraphQL */', ...graphqlTags] as const;
const blocksMap = new Map<string, Block[]>();

export const processor: Linter.Processor<Block | string> = {
  supportsAutofix: true,
  preprocess(code, filePath) {
    if (RELEVANT_KEYWORDS.every(keyword => !code.includes(keyword))) {
      return [code];
    }
    const extractedDocuments = parseCode({
      code,
      filePath,
      options: {
        ...graphqlTagPluckOptions
        skipIndent: true,
      },
    });...
```

Configured through graphql-config in the following file `graphql.config.js`:
```
module.exports = {
  projects: {
    default: {
      documents: './src/**/*.{tsx, ts, jsx, js}',
      operations: './src/**/*.{tsx, ts, jsx, js}',
      extensions: {
        graphqlTagPluck: {
          modules: [
            { 
              name: 'customTags`, 
              identifier: 'foo' 
            }, 
            { 
              name: 'customTags', 
              identifier: 'bar' 
            }
          ],
          globalGqlIdentifierName: ['foo', 'bar'],
          gqlMagicComment: '__nomagiccomment__',
        },
      },
    },
  },
}

```

**Describe alternatives you've considered**

It seems very clear in the code that custom tags are not supported, so I'm not sure if there are alternatives given that I am using custom tags.

**Additional context**

**Comment by B2o5T** [comment]
Nice catch! Accepted, thank you!

**Comment by JimmyPaolini** [comment]
Do I need repo permission to implement this?

**Comment by B2o5T** [comment]
Nope, just fork and sent a PR, otherwise I’ll do it by myself and include this change in next release
