### ISSUE TITLE
Parsing issue when graphql code itself contains "graphql" or "gql"

### ISSUE THREAD

**Issue by jlowcs** [B2o5T/graphql-eslint#1158]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Following [this change](https://github.com/B2o5T/graphql-eslint/pull/1040/files#diff-1c835bbcaef52ac0719495e2636542059f8fc470ff9e48aaa6d9155f4635e615L9), whenever any piece of code contains `graphql` or `gql`, that code will be preprocessed.

The issue with that is that something like this will report an error (in my case `Preprocessing error: Unexpected reserved word 'enum'`):

```
module.exports.typeDefs = gql`
  type Foo {
    """
    Lorem ipsum

    See https://github.com/graphql/graphql-spec/issues/488
    """
    metadata: JSON
  }
`
```

Same issue if a field is named `graphqlValue` for instance (which is less likely to happen).

**To Reproduce**

Create a file with the following contents:
```js
const gql = require('graphql-tag');

module.exports.typeDefs = gql`
  type Foo {
    """
    Lorem ipsum

    See https://github.com/graphql/graphql-spec/issues/488
    """
    metadata: JSON
  }
`
```

After running eslint, we get the following output:
```
/my/path/Foo.js
  0:0  error  Preprocessing error: Missing semicolon. (2:6)

✖ 1 problem (1 error, 0 warnings)
```

**Expected behavior**

No linting errors

**Environment:**

- OS: MacOS
- `@graphql-eslint/eslint-plugin`: 3.10.7
- Node.js: 18

**Additional context**

**Comment by B2o5T** [comment]
Hi @jlowcs ! Sorry for the silence, I can't reproduce it, can you add a simple reproduction repo? Can't reproduce on my side 🤨

**Comment by jlowcs** [comment]
I'll try to do that when I have some time

**Comment by B2o5T** [comment]
closed due silence
