### ISSUE TITLE
rule to require selecting __typename

### ISSUE THREAD

**Issue by joshribakoff-sm** [B2o5T/graphql-eslint#1159]
`graphql-codegen` generates types that imply `__typename` will always be present, but that's only the case if you actually fetch that field. Therefore, it would be nice to have a lint rule that forces all queries to select `__typename` on every type.

**Comment by B2o5T** [comment]
Hi! Do you tied this rule? https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/require-id-when-available.md#asarray-array This rule will be renamed in next major version since not only `id` field can be required but any field you want

**Comment by joshribakoff-sm** [comment]
Seems like it should work, but from a quick look it seems like I could only require one field (eg. not both `id` and `__typename`)

Also, there seems to maybe be a possible feature request for the `graphql-codegen` to *not* assume `__typename` will be present, unless it is actually selected. I wasn't sure if I should file a symmetrical issue there on the other repo, I'm assuming the maintainers are the same :)

**Comment by B2o5T** [comment]
Please take a look yet another time to documentation, `fieldName` option accept either string or array of strings

**Comment by B2o5T** [comment]
closing for now, feel free to ask if you still need help
