### ISSUE TITLE
Preprocessing error on invalid files

### ISSUE THREAD

**Issue by Lugribossk** [B2o5T/graphql-eslint#1161]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**
When typing in new code in a file makes it temporarily invalid Javascript/Typescript, IntelliJ will show an error banner with "ESLint: Preprocessing error". This only happens with this plugin enabled, and stops happening if I add a try/catch block in the preprocessor in https://github.com/B2o5T/graphql-eslint/blob/fffb1273f5eda8e3ff3ff15da52202c02be19639/packages/plugin/src/processor.ts#L14

**To Reproduce**
1. Configure a project to use Eslint and this plugin.
2. Open a file in that project that has syntax errors in IntelliJ.

**Expected behavior**
No error banner should be shown, similar to how other plugins handle invalid files.

**Environment:**

- OS: Windows 10
- `@graphql-eslint/eslint-plugin`: 3.10.7
- `eslint`: 8.23.1
- Node.js: 16.13.2
- IntelliJ: 2022.2.2

**Comment by B2o5T** [comment]
Hi @Lugribossk ! Can you add an example of invalid file?

**Comment by Lugribossk** [comment]
It looks like it might have to be a file that uses `gql`, but other than that any file with a syntax error will do, e.g.:

![image](https://user-images.githubusercontent.com/1399482/192152974-079708b3-bc17-46b0-9af3-4afadd85e257.png)

**Comment by B2o5T** [comment]
@Lugribossk can you confirm the presence of your issue on `3.11.1-alpha-20220926102745-dd5901a`  version?

**Comment by Lugribossk** [comment]
Yes, it still happens on that version.

**Comment by B2o5T** [comment]
I guess we can back `try`/`catch` statement, so the annoying popup in WebStrom will disappear, anyway ESLint will report about the problem while running eslint in terminal

### before
<img width="577" alt="image" src="https://user-images.githubusercontent.com/7361780/192277721-64b9b0d9-7c07-461d-abca-c8aeb81640b8.png">

### after
<img width="573" alt="image" src="https://user-images.githubusercontent.com/7361780/192277601-bcfc2d54-ff43-49fa-b7f5-dc6e2d290ca6.png">

fixed in `@graphql-eslint/eslint-plugin@3.11.1`

**Comment by Lugribossk** [comment]
Awesome, thank you for the fix!

And I think it makes sense to see the error in the terminal, since you run that when you want to know about errors. While the banner shows up when you're in the middle of editing a file.
