### ISSUE TITLE
3.11.x crashes when using config without `default` project

### ISSUE THREAD

**Issue by notjosh** [B2o5T/graphql-eslint#1169]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Upgrading from `3.10.7` to `3.11.0` and `3.11.1` causes a crash on startup in our project, as we do not have a `default` project configured.

**To Reproduce**

Our schema does not contain a `default` projects - each of our projects are explicitly named.

#1156 introduced a call to `graphQLConfig().getDefault()` which will [throw](https://github.com/kamilkisiela/graphql-config/blob/9eb3df65b9fb333678c5a03ddb50d439655aa47b/src/config.ts#L152-L154).

For example, running `yarn lint` throws an error on initialisation:

```
ESLint: 8.23.1

[ProjectNotFoundError: Failed to load plugin '@graphql-eslint' declared in '.eslintrc.json#overrides[2]': Project 'default' not found
Referenced from: /path/to/.eslintrc.json] {
  name: 'ProjectNotFoundError',
  message: "Failed to load plugin '@graphql-eslint' declared in '.eslintrc.json#overrides[2]': Project 'default' not found\n" +
    'Referenced from: /path/to/.eslintrc.json'
}
error Command failed with exit code 2.
```

It looks like the code expects to gracefully handle this as an optional, but [`getDefault()`](https://github.com/kamilkisiela/graphql-config/blob/2c568f1ee2d45bc46613b86b12fcfab82b1393aa/src/config.ts#L178-L180) will never return an optional.

I believe the fix should use `getProjectForFile()`, to ensure the configuration is associated with the correct project.

**Expected behavior**

Running `yarn lint` should work as 3.10.7 did.

**Environment:**

- OS: macOS 12.6
- `@graphql-eslint/eslint-plugin`: 3.11.1
- Node.js: v16.14.2

**Additional context**

**Comment by B2o5T** [comment]
Hey @notjosh, could you try `3.11.2-alpha-20220926143611-7437e15` alpha version? And I'll release it asap

**Comment by notjosh** [comment]
Still no good - `getDefault()` still throws, so `preprocess()` fails repeatedly. If you let it keep running, eventually it segfaults...which is fun :) I'm surprised it doesn't actually show the error...the only way I found this was by adding a `console.log()` inside of `preprocess()`

I did get it working by replacing `.getDefault()` with `.getProjectForFile(filePath)` [here](https://github.com/B2o5T/graphql-eslint/pull/1170/files#diff-1c835bbcaef52ac0719495e2636542059f8fc470ff9e48aaa6d9155f4635e615R21).

It's probably worth putting a `try/catch` around that to fall back to skip the block, so that `preprocess()` doesn't fail if `graphql-config` can't parse the config.

**Comment by B2o5T** [comment]
@notjosh `3.11.2-alpha-20220926144959-f269795` should be good :))

**Comment by notjosh** [comment]
Yup, that one's working for me.

**Comment by B2o5T** [comment]
Amazing! thank you for the quick feedback, will be released now 😜
