### ISSUE TITLE
Composing generic and specific rules for the same node type

### ISSUE THREAD

**Issue by rperryng** [B2o5T/graphql-eslint#1179]
I was hoping to define a "base" `.eslintrc.js` ruleset and then use project-specific `.eslintrc.js` files that "add exceptions".  I cannot use the `# eslint-disable ...` since sometimes the schema is generated from code rather than being hand-written.

At my org we have several GraphQL schemas.  Overtime we would like them to all conform to the same styles, as enforced by `graphql-eslint`.

For example, using `UPPER_CASE` for `EnumValueDefinition`:

```javascript
// .eslintrc.js
module.exports = {
  overrides: [
    ...
    rules: {
      '@graphql-eslint/naming-convention': [
        'error',
        {
          EnumValueDefinition: {
            style: 'UPPER_CASE',
          },
        },
      ]
    },
  ]
};
```

Within this repo are several of our GraphQL APIs, so we can use one set of rules to use on them all.

Since we've only enforced these linting rules recently, we have several different offenses in different schemas that we can't immediately change since it would be a breaking change.

In these cases I was hoping to extend the "base" ruleset with rules that use the AST selectors in order to "add" exceptions.

```javascript
// schemas/some-service-1/.eslintrc.js
module.exports = {
  extends: "../../.eslintrc.js",
  rules: {
    '@graphql-eslint/naming-convention': [
      'error',
      {
        'EnumValueDefinition[parent.name.value=DayOfWeek]': {
          style: 'UPPER_CASE',
          ignorePattern: '^(monday)',
        },
      },
    ],
  }
};
```

Unfortunately, `extends` doesn't merge the rules additively (an `eslint` thing, I recognize), so now the only naming convention enforced is the one with the eslint selector.

Though, even if I were to create a configuration that explicitly combines both together:

```javascript
      rules: {
        '@graphql-eslint/naming-convention': [
          'error',
          {
            EnumValueDefinition: {
              style: 'UPPER_CASE',
            },
            'EnumValueDefinition[parent.name.value=FooBar]': {
              style: 'UPPER_CASE',
              ignorePattern: '^(foo)'
            }
          },
        ],
      },
```

the rule definition without the eslint selector would still report the offense for the `foo` entry in the `FooBar` enum.

I was hoping to define a "base" ruleset and then use `.eslintrc.js` files that "add exceptions".  I cannot use the `# eslint-disable ...` in this particular case since sometimes the schema is generated from code rather than being hand-written.

**Describe alternatives you've considered**

1. **Option 1**: Define `EnumValueDefinition` without a selector and add all existing offenses to it

    ```javascript
          rules: {
            '@graphql-eslint/naming-convention': [
              'error',
              {
                EnumValueDefinition: {
                  style: 'UPPER_CASE',
                  ignorePattern: '^(foo|monday|tuesday)'
                },
              },
            ],
          },
    ```

    This approach can't scope the `ignorePattern` to specific `EnumTypeDefinition`s.  Pretty minor.
    
    The real crux of this approach is that I have to ensure all of the rule definitions in the "base" `.eslintrc` (for example, naming conventions for _other_ types) need to also be included.
    
    The only way around this I think would be to write some custom tooling to construct the config dynamically, something like: 
    
    ```javascript
    const extendConfig = require('../../extendConfig.js');
    
    module.exports = extendConfig({
      EnumValueDefinition: {
        ignore: ['foo', 'monday', 'tuesday']
      },
    });
    ```

**Additional context**

I'm not sure if this falls out of scope for the project, since it seems (appropriately) that a rule's configuration for specific node types can only be defined once.

But is there some other approach I can do to define a "base" configuration and easily add exceptions (using the `eslint` selectors or some other approach) from within another `.eslintrc` configuration?

**Comment by B2o5T** [comment]
I suggest you write your own rule for your specific case
