### ISSUE TITLE
rule @graphql-eslint/unique-type-names does not check multiple files

### ISSUE THREAD

**Issue by jbrangwyn** [B2o5T/graphql-eslint#1208]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

If I define two types in a single file this rule works fine (displays an error), but if the duplicate types are in different files it does not display an error.

**To Reproduce**
Define the same type in multiple files.

**Expected behavior**
An error should be displayed when running eslint.

**Environment:**

- OS: Win 10
- `@graphql-eslint/eslint-plugin`: 3.12.0
- Node.js: 16.15.0

**Additional context**

**Comment by B2o5T** [comment]
worked as expected since we are unable to build GraphQL schema, I tried a lot of things but this cannot be fixed
more info in my comment https://github.com/B2o5T/graphql-eslint/issues/787#issuecomment-1003617324
