### ISSUE TITLE
Plugin doesn't work with esm project configuration

### ISSUE THREAD

**Issue by ZiiMakc** [B2o5T/graphql-eslint#1276]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

VSCode eslint not working and shows an error:
```
TSError: Cannot read config file: \apps\api\.eslintrc.cjs
Error: ⨯ Unable to compile TypeScript:
error TS5095: Option 'preserveValueImports' can only be used when 'module' is set to 'es2015' or later.
```

tsconfig.json:
```
 "module": "ES2022", // doesn't effect anything
 "moduleResolution": "node",  // doesn't effect anything
 "preserveValueImports": true // false fixes the problem, but it's not a solution
```

Config:
```
module.exports = {
  root: true,
  overrides: [
    {
      files: ['*.ts'],
      processor: '@graphql-eslint/graphql',
    },
    {
      files: ['*.graphql'],
      extends: ['plugin:@graphql-eslint/schema-all'],
      parserOptions: {
        schema: '../../common/generated/api-schema.graphql',
      },
    },
  ],
};
```

**Expected behavior**

VScode should work correctly with plugin

**Environment:**

- OS: Windows
- `@graphql-eslint/eslint-plugin`: "3.13.1"
- `"eslint": "8.28.0",`
- Node.js: 18

**Comment by B2o5T** [comment]
Could you provide reproduction repo?

**Comment by B2o5T** [comment]
closed due silence
