### ISSUE TITLE
ESLint suggestions for "Did you mean" messages

### ISSUE THREAD

**Issue by FloEdelmann** [B2o5T/graphql-eslint#1309]
The lint issues by the following rules can provide "Did you mean" suggestions in the reported error message:

* [`@graphql-eslint/fields-on-correct-type`](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/fields-on-correct-type.md)
* [`@graphql-eslint/known-argument-names`](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/known-argument-names.md)
* [`@graphql-eslint/known-type-names`](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/known-type-names.md)
* [`@graphql-eslint/possible-type-extension`](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/possible-type-extension.md)
* [`@graphql-eslint/scalar-leafs`](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/scalar-leafs.md)
* [`@graphql-eslint/value-literals-of-correct-type`](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/value-literals-of-correct-type.md)

It is currently not possible to use that suggestion in the editor (e.g. VS Code). It would be great to add [ESLint suggestions](https://eslint.org/docs/latest/developer-guide/working-with-rules#providing-suggestions) to those rules, so that the suggestions can be semi-automatically be applied.

Since those all wrap validations from https://github.com/graphql/graphql-js, upstream changes might be necessary. (See also the [search results for `repo:graphql/graphql-js "Did you mean" path:src/validation/__tests__/*Rule-test.ts`](https://github.com/search?q=repo%3Agraphql%2Fgraphql-js+%22Did+you+mean%22+path%3Asrc%2Fvalidation%2F__tests__%2F*Rule-test.ts&type=code).)

### Example

```graphql
query Test($id: string) { … }
```

Lint error: `Unknown type "string". Did you mean "String"?`
**Expected suggestion:** `Change to "String".`

**Comment by B2o5T** [comment]
Sound good, thanks for the catch! will try to add `suggestions` this week

**Comment by B2o5T** [comment]
suggestions can be tested in the following alpha version `3.14.0-alpha-20221220000306-eefc8db`

**Comment by FloEdelmann** [comment]
Cool, this seems to work pretty well!
