### ISSUE TITLE
New rule `lone-executable-definition`

### ISSUE THREAD

**Issue by FloEdelmann** [B2o5T/graphql-eslint#1311]
**Is your feature request related to a problem? Please describe.**

To keep a better overview over all queries and fragments, I want to enforce that every operation, fragment, subscription and mutation is located in a separate file:

```graphql
query Foo { … }
query Bar { … } # FAIL
fragment Baz on Foo { … } # FAIL
```

**Describe the solution you'd like**

A new rule `lone-operation`. However, are fragments "operations"? If no, then a better rule name should be found.

**Comment by B2o5T** [comment]
Sound good, would you work on this rule?
this script will help you bootstrap your rule https://github.com/B2o5T/graphql-eslint/blob/master/scripts/create-rule.ts

and about rule name we can name it with `lone-executable-definition`
