### ISSUE TITLE
Support multiple styles in the OperationDefinition rule

### ISSUE THREAD

**Issue by dakshas** [B2o5T/graphql-eslint#1327]
**Is your feature request related to a problem? Please describe.**

My project has operation names that are either in camelCase or PascalCase. I want to enforce this using eslint. 
graphql-eslint does not support checking against multiple styles in a one of manner.

**Describe the solution you'd like**

Add support to check the operation name style against multiple options
so something like 
```
rules:
      '@graphql-eslint/naming-convention':
        - error
        - OperationDefinition:
            style: 
             - camelCase
             - PascalCase
```

**Comment by B2o5T** [comment]
Sorry, but I don't want to include this to default rule
