### ISSUE TITLE
[known-fragment-names] Option to fail if the fragment was not imported

### ISSUE THREAD

**Issue by adrienharnay** [B2o5T/graphql-eslint#1365]
**Is your feature request related to a problem? Please describe.**

When working on the front-end and doing codegen with graphql-code-generator, I sometimes get runtime errors because I used a fragment I did not import.

**Describe the solution you'd like**

It would be great if `known-fragment-names` could have an option to report an error if a fragment has been used, it's defined in another file OK but it has not been `#import`ed.

**Describe alternatives you've considered**

/

**Additional context**

Have a nice day!

**Comment by B2o5T** [comment]
it was added by https://github.com/B2o5T/graphql-eslint/pull/1443 new rule

**Comment by adrienharnay** [comment]
Thank you!!!
