### ISSUE TITLE
New rule: require import expressions for fragments

### ISSUE THREAD

**Issue by FloEdelmann** [B2o5T/graphql-eslint#1413]
`graphql-let` and other tools rely on `# import` expressions in GraphQL files to resolve fragments defined in other files: https://github.com/piglovesyou/graphql-let#how-to-import-graphql-from-another-document-especially-graphql-fragment

I'd like to suggest a rule that requires such a comment when a fragment is used:

### Fail

```graphql
query MyQuery {
  fooField {
    ...Foo
#      ^^^ Expected 'Foo' fragment to be imported
  }
}
```

```graphql
# import 'someOtherFile.graphql'

query MyQuery {
  fooField {
    ...Foo
#      ^^^ Expected 'Foo' fragment to be imported
  }
}
```

### Pass

```graphql
# import Foo from 'someOtherFile.graphql'

query MyQuery {
  fooField {
    ...Foo
  }
}
```

```graphql
#import Foo from 'someOtherFile.graphql'

query MyQuery {
  fooField {
    ...Foo
  }
}
```

**Comment by B2o5T** [comment]
Accepted, you can work on it and I’ll review it
