### ISSUE TITLE
How does this work with graphql-tag literal in JS/TS files?

### ISSUE THREAD

**Issue by sarink** [B2o5T/graphql-eslint#1449]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

An extremely common setup is, rather than using `.graphql` files, to declare graphql via `gql` string literals inside code files.

An example showing this doesn't appear to be documented anywhere (except, "works with gql" tags)

Furthermore, lots of folks are probably using the `@typescript-eslint/parser`, and I kinda thought the whole point of special parsers was so users could pick one of the three major [supported parsers](https://eslint.org/docs/latest/use/configure/plugins#configure-a-parser) based on their configuration? I'm finding this conceptually a bit confusing to use two different parsers on the same file.

Migrating from [eslint-plugin-graphql](https://github.com/apollographql/eslint-plugin-graphql), the setup for this tool seems really complex, and the documentation for any configuration other than using it to lint `.graphql` files, is nonexistent.

Presumably, what I'm trying to do is completely possible, and I am simply misunderstanding something. Can anyone help convert the following `eslintrc.js` from eslint-plugin-graphql to @graphql-eslint?

```
const schemaJson = require('./common/api-schema.json');

module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module',
  },
  extends: [],
  plugins: ['graphql', '@typescript-eslint'],
  rules: {
    '@typescript-eslint/naming-convention': ['warn', { selector: 'class', format: ['PascalCase'] }],
    '@typescript-eslint/no-array-constructor': 'warn',
    '@typescript-eslint/no-unused-vars': ['warn', { args: 'none' }],
    'graphql/capitalized-type-name': ['warn', { schemaJson }],
    'graphql/named-operations': ['warn', { schemaJson }],
    'graphql/template-strings': ['error', { env: 'apollo', schemaJson }],
    'no-var': 'warn',
    'prefer-arrow-callback': 'warn',
    'prefer-const': 'warn',
    radix: 'warn',
  },
};
```

**Comment by sarink** [comment]
I should clarify, I tried appending the following config:

```
  overrides: [
    {
      files: ['*.tsx', '*.ts', '*.jsx', '*.js'],
      processor: '@graphql-eslint/graphql',
    },
    {
      files: ['*.graphql'],
      extends: 'plugin:@graphql-eslint/operations-recommended',
      parserOptions: {
        schema: './common/api-schema.json',
      },
    },
  ],
```

and, while it doesn't error, it doesn't seem to work
```
gql`
  query($foo: asdf) {
    adsf
  }
`;
```
does not fail listing

**Comment by B2o5T** [comment]
Duplicate https://github.com/B2o5T/graphql-eslint/issues/1427

**Comment by sarink** [comment]
@B2o5T it is not a duplicate, as you can see, I have not missed adding the `parser`, because I am using the `extends: 'plugin:@graphql-eslint/operations-recommended',`.

**Comment by sarink** [comment]
Full config
```
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module',
  },
  extends: [],
  plugins: ['graphql', '@typescript-eslint'],
  rules: {
    '@typescript-eslint/naming-convention': ['warn', { selector: 'class', format: ['PascalCase'] }],
    '@typescript-eslint/no-array-constructor': 'warn',
    '@typescript-eslint/no-unused-vars': ['warn', { args: 'none' }],
    'no-var': 'warn',
    'prefer-arrow-callback': 'warn',
    'prefer-const': 'warn',
    radix: 'warn',
  },
  overrides: [
    {
      files: ['*.tsx', '*.ts', '*.jsx', '*.js'],
      processor: '@graphql-eslint/graphql',
    },
    {
      files: ['*.graphql'],
      extends: 'plugin:@graphql-eslint/operations-recommended',
      parserOptions: {
        schema: './common/api-schema.json',
      },
    },
  ],
};
```

**Comment by B2o5T** [comment]
you have incorrect eslint config, working example https://github.com/B2o5T/graphql-eslint/blob/4cb913b4d16f2c281f34ea595629e4ad5abaede9/examples/monorepo/.eslintrc.cjs

**Comment by sarink** [comment]
```
  // ❗️ It's very important that you don't have any rules configured at the top-level config,
  // and to move all configurations into the overrides section. Since JavaScript rules
  // can't run on GraphQL files and vice versa, if you have rules configured at the top level,
  // they will try to also execute for all overrides, as ESLint's configs cascade
  ```
  If we use this plugin, then we're not allowed to configure any ` rules` ??

**Comment by B2o5T** [comment]
> The way this plugin works is against the way the eslint plugin system works, and different from how every other eslint plugin works. I'm not sure why this design was chosen, but it makes it difficult and awkward for consumers.

ESLint plugin system was always cascaded, even in v8 https://eslint.org/blog/2022/08/new-config-system-part-2/

You can use whatever you want I don't care about what you use and what you stick

**Comment by esquevin** [comment]
Would be worth it to document it in https://the-guild.dev/graphql/eslint/docs/getting-started#apply-plugin-to-graphql-definitions-defined-in-code-files

Knowing that allowed me to have the linting finally work on an existing codebase after struggling for a long time.

Thx for the great package =)

**Comment by sarink** [comment]
I just don't understand how anyone can adopt this into their config if it means not writing any top-level `rules`, or why that's not the very first thing mentioned in all caps in the documentation.

Is our project a weird anomaly for specifying `rules`? It's the very first thing eslint shows you to do [in their docs](https://eslint.org/docs/latest/use/configure/configuration-files-new#configuration-file)

**Comment by sarink** [comment]
I just don't understand how anyone can adopt this into their config if it means not writing any top-level `rules`? Or why that's not mentioned in all caps at the top of the documentation?

Is our project a weird anomaly for specifying `rules`? It's literally the very first thing eslint shows you to do [in their docs](https://eslint.org/docs/latest/use/configure/configuration-files-new#configuration-file). Rules are for rules, overrides are for overriding those rules. Your plugin has broken the most standard contract of eslint configuration

> You can use whatever you want I don't care about what you use and what you stick

Thanks ❤️

**Comment by jhirn** [comment]
> I just don't understand how anyone can adopt this into their config if it means not writing any top-level `rules`? Or why that's not mentioned in all caps at the top of the documentation?
> 
> Is our project a weird anomaly for specifying `rules`? It's literally the very first thing eslint shows you to do [in their docs](https://eslint.org/docs/latest/use/configure/configuration-files-new#configuration-file). Rules are for rules, overrides are for overriding those rules. Your plugin has broken the most standard contract of eslint configuration
> 
> > You can use whatever you want I don't care about what you use and what you stick
> 
> Thanks ❤️

I know I pretty much lost 3 hours trying to get this to work and it still doesn't. Luckily the VSCode plugin is showing errors but not though ESLint. Since it's a solo project that's good enough for me but it's pretty odd to have to move everything into overrides and absurd to not mention in the documentation.
