### ISSUE TITLE
Parser can not find types when multiple files are used

### ISSUE THREAD

**Issue by keh007** [B2o5T/graphql-eslint#1458]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

When using a single file per type (i.e. schema.graphql, query.graphql, mutation.graphql, myType.graphql, myOthertype.graphql, etc.) parser will not load, parse, or search files for types but instead throws an error.  The only workaround is to combine every type of a very large schema into one monster file (uggghhh).

**To Reproduce** Steps to reproduce the behavior:

Create a file called Schema.graphql:
schema {
     query: Query
}

Create a file called Query.graphql
type Query {
     myType(id: String) : MyType
}

Create a file called MyType.graphql
type MyType {
     id: string
     name: string
}

create .eslintrc.js (modify files property to point to folder with .graphql files created from above)
module.exports = {
    "overrides": [
      {
        "files": ["*.js"],
        "processor": "@graphql-eslint/graphql"
      },
      {
        "files": [
          "./schema/**/*.graphql"
        ],
        "parser": "@graphql-eslint/eslint-plugin",
        "parserOptions": {
          "schema" : "./schema/schema.graphql"
        },
        "plugins": ["@graphql-eslint"],
        "extends": "plugin:@graphql-eslint/schema-recommended",
        }
   ]
}
       
run linter

It's a crap shoot if the files get loaded properly or not.  It seems like if you get lucky and the files are loaded in a good order it works.  However, as you get more files and files get edited, deleted, new files added, etc. the likely hood of being lucky with loading all files in order diminishes.

Workaround is to create one ugly uberfile with the entire schema (uggghhh)

**Expected behavior**

All files should be read and scanned properly for linting the way the codegen tool works.

**Environment:**

- OS:
- `@graphql-eslint/eslint-plugin`: "^3.16.0"
- Node.js:

**Additional context**

**Comment by B2o5T** [comment]
Please create a minimal reproduction repo

**Comment by B2o5T** [comment]
closed due silence
