### ISSUE TITLE
Too many blank lines at the beginning of file. Max of 0 allowed.(no-multiple-empty-lines)

### ISSUE THREAD

**Issue by mrjackyliang** [B2o5T/graphql-eslint#1459]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
   - [x] a. A workaround has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Enabling the GraphQL ESLint plugin causes this error in the `graphql.ts` file:
```
ESLint: Too many blank lines at the beginning of file. Max of 0 allowed.(no-multiple-empty-lines)
```

**To Reproduce** Steps to reproduce the behavior:

I am using the [Next.js Apollo Server](https://github.com/vercel/next.js/blob/canary/examples/api-routes-apollo-server/pages/api/graphql.ts) example to begin.

I installed these packages (not included in the example project):
```
{
  "devDependencies": {
    "@graphql-eslint/eslint-plugin": "3.16.0",
    "eslint": "8.34.0",
    "eslint-config-airbnb": "19.0.4",
    "eslint-config-airbnb-typescript": "17.0.0",
    "eslint-config-next": "13.1.6",
  }
}
```

My ESLint config:
```
{
  "extends": [
    "airbnb",
    "next/core-web-vitals"
  ],
  "overrides": [
    {
      "extends": [
        "airbnb-typescript"
      ],
      "files": [
        "*.ts",
        "*.tsx"
      ],
      "parser": "@typescript-eslint/parser",
      "parserOptions": {
        "project": [
          "./tsconfig.json"
        ]
      }
    },
    {
      "files": [
        "*.graphql"
      ],
      "parser": "@graphql-eslint/eslint-plugin",
      "plugins": [
        "@graphql-eslint"
      ]
    },
    {
      "files": [
        "*.ts"
      ],
      "processor": "@graphql-eslint/graphql"
    }
  ]
}
```

**Expected behavior**

There shouldn't be any ESLint errors. However, a workaround is to put a pound sign (a comment) right after the beginning tick (`) like the example below:

```
export const typeDefs = gql`#   <---- that pound fixes the error ¯\_(ツ)_/¯
  type Query {
    users: [User!]!
    user(username: String): User
  }
  type User {
    name: String
    username: String
  }
`;
```

**Environment:**

- OS: macOS Ventura 13.1
- `@graphql-eslint/eslint-plugin`: 3.16.0
- Node.js: 16.18.1

**Additional context**

The StackBlitz package.json doesn't show a version. Says `workspace:*`

**Comment by B2o5T** [comment]
It happens because somewhere you enabled `no-multiple-empty-lines` for all files and it runs for graphql files even extracted from code files

Just disable this rule for graphql files or refactor your config, take a look at working examples in the examples folder

**Comment by mrjackyliang** [comment]
I noticed that after disabling the `airbnb` package. But yes, doing the following does indeed fix the error:

```
    {
      "files": [
        "*.graphql"
      ],
      "parser": "@graphql-eslint/eslint-plugin",
      "plugins": [
        "@graphql-eslint"
      ],
      "rules": {
        "no-multiple-empty-lines": "off"
      }
    },
    {
      "files": [
        "*.ts"
      ],
      "processor": "@graphql-eslint/graphql"
    }
```

Maybe I should start selectively applying plugins to files so they're not global 🤔

**Comment by B2o5T** [comment]
Yes, you should not contain global configuration, also in the future versions of ESLint 9 specifying something globally will be impossible since the config system will be changed.

**Comment by mrjackyliang** [comment]
> Yes, you should not contain global configuration, also in the future versions of ESLint 9 specifying something globally will be impossible since the config system will be changed.

That's actually good to hear. ESLint configurations has always been very confusing to me.
