### ISSUE TITLE
Cannot parse graphql files with @link for apollo subgraphs

### ISSUE THREAD

**Issue by andywgarcia** [B2o5T/graphql-eslint#1505]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

`Parsing error: [graphql-eslint] Error while loading schema: Unknown directive "@link"`

When using apollo subgraph directives

**To Reproduce** Steps to reproduce the behavior:

I am trying to lint our schema files for an Apollo subgraph, which all extend a remote schema using a line like `extend schema @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])`. See https://www.apollographql.com/docs/apollo-server/using-federation/apollo-subgraph-setup/#2-opt-in-to-federation-2). I have my graphql files set up like the following:

```

// type-one.graphql

extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.3", import: ["@shareable"])

type TypeOne @shareable {
   id: ID!
}

// type-two.graphql

extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.3", import: ["@shareable"])

type TypeTwo @shareable {
   id: ID!
}

```

**Expected behavior**

Parsing should succeed for .graphql files using directives that the parser doesn't recognize (or allow them to be skipped).

**Environment:**

- OS: MacOS 13.2.1
- `@graphql-eslint/eslint-plugin`: 3.16.1
- Node.js: 16.19.1

**Additional context**

I found `@graphql-eslint/known-directives` and set that to off, but the issue appears to be the parser, not the rules.

**Comment by B2o5T** [comment]
try https://github.com/B2o5T/graphql-eslint/discussions/1063#discussioncomment-2721295
