### ISSUE TITLE
In “Writing Custom Rules” not clear how to apply the rule

### ISSUE THREAD

**Issue by sergey-rogatin** [B2o5T/graphql-eslint#1506]
In the [Writing Custom Rules](https://eslint.org/docs/latest/extend/custom-rules) section, it's not clear how to actually make the custom rule work with eslint config. The way recommended by the eslint documentation is to create a separate npm module for a plugin, which seems like overkill to me.

This is how I ended up doing it through monkey patching in `.eslintrc.js`
```javascript
const rule = require('.myRule.js');
const graphqlPlugin = require('@graphql-eslint/eslint-plugin');
graphqlPlugin.rules['my-rule-name'] = rule;
```
This seems kinda janky, but it works. Is it the intended way? Thank you for your work!

**Comment by B2o5T** [comment]
```js
```
