### ISSUE TITLE
Support for Naming Conventions Based on Field Assigned Type

### ISSUE THREAD

**Issue by louisscruz** [B2o5T/graphql-eslint#1521]
**Is your feature request related to a problem? Please describe.**

As a user of `graphql-eslint`, I'd like to be able to enforce certain naming conventions for fields based on the assigned type of the field. For example, I might want to enforce that all `Boolean` schema fields are named such that they have a prefix of `is` or `has`. 

**Describe the solution you'd like**

I have not dug very far, but It seems like it might be possible to extend the current [naming-convention rule](https://the-guild.dev/graphql/eslint/rules/naming-convention) to allow for this kind of configuration.

Correct:

```graphql
# eslint @graphql-eslint/naming-convention: ['error', { 'FieldDefinition[assignedType.value=Boolean]': { requiredPrefixes: ['is', 'has'] } }]
 
type User {
  isVerified: Boolean!
}
```

Incorrect:

```graphql
# eslint @graphql-eslint/naming-convention: ['error', { 'FieldDefinition[assignedType.value=Boolean]': { requiredPrefixes: ['is', 'has'] } }]
 
type User {
  verified: Boolean!
}
```

**Describe alternatives you've considered**

If it's not possible to extend `naming-convention`, perhaps a new rule could be made to handle this case? It seems like it'd be better to extend the existing rule though.

**Additional context**

If it seems like extending `naming-convention` might be acceptable to account for this case, I might be able to help with implementing it.

**Comment by B2o5T** [comment]
PR is welcome for a new option for an existing rule

Your selectors will look like
```js
          'FieldDefinition[gqlType.name.value=Boolean]': {
            requiredPrefixes: ['is', 'has']
          },
          'FieldDefinition[gqlType.gqlType.name.value=Boolean]': {
            requiredPrefixes: ['is', 'has']
          },
          'FieldDefinition[gqlType.gqlType.gqlType.name.value=Boolean]': {
            requiredPrefixes: ['is', 'has']
          },
          'FieldDefinition[gqlType.gqlType.gqlType.gqlType.name.value=Boolean]': {
            requiredPrefixes: ['is', 'has']
          },
```

they will match the following `name*` fields

```graphql
type User {
  id: ID!
  name: Boolean
  name2: Boolean!
  name3: [Boolean!]
  name4: [Boolean!]!
}
```

**Comment by louisscruz** [comment]
Great, thanks for the direction!

I have a branch locally where this is nearly fleshed out. Hoping to get a PR together soon.

**Comment by louisscruz** [comment]
Ok, an implementation is over here: https://github.com/B2o5T/graphql-eslint/pull/1540
