### ISSUE TITLE
Rule to enforce trailing commas

### ISSUE THREAD

**Issue by lwasyl** [B2o5T/graphql-eslint#1559]
**Is your feature request related to a problem? Please describe.**
Trailing commas are a nice practice that avoids unnecessary diffs when adding or removing parameters/arguments etc. at the last position

**Describe the solution you'd like**
A new rule that would enforce a trailing comma on last lines of lists

**Describe alternatives you've considered**

**Additional context**

**Comment by B2o5T** [comment]
Sorry but I don't plan to any rules that validates `semi` or `spaces`. Please request your feature in [`prettier` repository](https://github.com/prettier/prettier)
