### ISSUE TITLE
[Docs] It's unclear that you need a GraphQL config file

### ISSUE THREAD

**Issue by crutchcorn** [B2o5T/graphql-eslint#1564]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [x] 2. A failing test has been provided
- [x] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

The docs do not currently make it clear that you need to have a [GraphQL Config](https://the-guild.dev/graphql/config/docs) file. As someone who went from "Generating TS from GQL" (which only requires a `codegen.ts` file to adding ESLint, I was very confused by some of the errors I was getting. 

**To Reproduce** Steps to reproduce the behavior:

1) Remove the GQL Config file
2) Run ESLint on project
3) See the following errors:

```
/project/src/store/user-slice.ts
  0:0  error  Preprocessing error: File '/project/src/store/user-slice.ts' doesn't match any project
```

**Expected behavior**

Provide a clearer error message saying to add a config file and/or a mention of including a GQL Config file in the project's "Installation" or "Setup" guide

**Environment:**

- OS:
- `@graphql-eslint/eslint-plugin`: `3.18.0`
- Node.js: `18.13.0`

**Additional context**

I'm happy to make a PR to improve the error message and/or docs

**Comment by B2o5T** [comment]
graphql-config file is not required, please provide reproduction repo
