### ISSUE TITLE
One syntax error in a schema file triggers identical errors in other GraphQL files

### ISSUE THREAD

**Issue by hokaccha** [B2o5T/graphql-eslint#1582]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

If there are multiple GraphQL schema files, a syntax error in one schema file will cause all other schema files to report the same error.

**To Reproduce** Steps to reproduce the behavior:

https://stackblitz.com/edit/github-gtadcw

There are three schema files:

`root.graphqls`

```graphql
type Query {
  foo: Foo
  bar: Bar
}
```

`foo.graphqls` (this file has a syntax error due to a missing `}`)

```graphqls
type Foo {
  id: ID!
```

`bar.graphqls`

```graphql
type Bar {
  id: ID!
}
```

The expected output when running ESLint should be to report the error only in the `foo.graphqls` file. However, it reports the same error for all files on the third line.

Current ESLint output:

```
$ eslint .

/.../schema/bar.graphqls
  3:0  error  Parsing error: [graphql-eslint] Error while loading schema: Syntax Error: Expected Name, found <EOF>

/.../schema/foo.graphqls
  3:0  error  Parsing error: [graphql-eslint] Syntax Error: Expected Name, found <EOF>

/.../schema/root.graphqls
  3:0  error  Parsing error: [graphql-eslint] Error while loading schema: Syntax Error: Expected Name, found <EOF>

✖ 3 problems (3 errors, 0 warnings)
```

**Expected behavior**

Expected ESLint output:

```
$ eslint .

/.../schema/foo.graphqls
  3:0  error  Parsing error: [graphql-eslint] Syntax Error: Expected Name, found <EOF>

✖ 1 problems (1 errors, 0 warnings)
```

**Environment:**

- OS: macOS 13.2.1
- `@graphql-eslint/eslint-plugin`: 3.18.0
- Node.js: v18.14.0

**Additional context**

**Comment by B2o5T** [comment]
Known limitation, unable to fix
