### ISSUE TITLE
require-nullable-result-in-root: TypeError: Cannot read properties of undefined (reading 'kind')

### ISSUE THREAD

**Issue by mat813** [B2o5T/graphql-eslint#1663]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

When I ran eslint, it now errors out with:

```
Oops! Something went wrong! :(

ESLint: 8.41.0

TypeError: Cannot read properties of undefined (reading 'kind')
Occurred while linting ./graphql/resolver/auth/typedefs/query-authed.graphql:1
Rule: "@graphql-eslint/require-nullable-result-in-root"
    at getNodeName (./node_modules/@graphql-eslint/eslint-plugin/cjs/utils.js:128:18)
    at ObjectTypeDefinition,ObjectTypeExtension (./node_modules/@graphql-eslint/eslint-plugin/cjs/rules/require-nullable-result-in-root.js:58:74)
    at ruleErrorHandler (./node_modules/eslint/lib/linter/linter.js:1050:28)
    at ./node_modules/eslint/lib/linter/safe-emitter.js:45:58
```

**To Reproduce** Steps to reproduce the behavior:

It errors out with that file:

```
extend type Query {
  authed: Boolean! @auth(requires: ANY)
}
```

**Expected behavior**

Well, I don't really know, but not breaking eslint would be nice.

**Environment:**

- OS:6.2.13-zen-1-zen GNU/Linux
- `@graphql-eslint/eslint-plugin`:3.18.0
- Node.js:v20.2.0

**Comment by B2o5T** [comment]
Thanks, will be fixed asap

**Comment by mat813** [comment]
To add more context, (I should not open issues when I get to the office and the brain has not completely finished booting,) we have a very large app and to keep it maintainable, we have hundreds of small graphql files that each have only one definition, and they are all compiled into a large schema.graphql file (and types and other stuff).

**Comment by nishtahir** [comment]
Just for additional context. Looks like the same issue raised here https://github.com/B2o5T/graphql-eslint/issues/1656#issuecomment-1559628411
