### ISSUE TITLE
Parsing error: Syntax Error: Cannot parse the unexpected character "<"

### ISSUE THREAD

**Issue by enzojavier-desimone** [B2o5T/graphql-eslint#1664]
Hi,

After long research and testing, I only could find this related information https://github.com/B2o5T/graphql-eslint/issues/544#issuecomment-905508958 which suggests that when placing the rules in `overrides` it throws the error

Command
```
npx eslint -c .eslintrc.json query.graphql
```

Output
```
/fragment.graphql
  1:5  error  Parsing error: [graphql-eslint] Syntax Error: Unexpected character: "<"
```

.eslintrc.json (shorten)
```
{
  "root": true,
  "plugins": [
    "@nrwl/nx",
    "prettier",
    "import",
    "unused-imports",
    "@graphql-eslint"
  ],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx"],
      "extends": ["plugin:@nrwl/nx/typescript"],
      "rules": {        
        "@typescript-eslint/no-var-requires": "off"
      }
    },
    {
      "files": ["*.graphql"],
      "parser": "@graphql-eslint/eslint-plugin",
      "plugins": ["@graphql-eslint"],
      "rules": {
        "@graphql-eslint/unique-fragment-name": "error",
      },
      "parserOptions": {
        "schema": ".*.graphql",
        "operations": "*.graphql"
      }
    }
  ]
}
```

The `query` file does not really matter, we have this error with any `.graphql` file `query`, `fragment`, or `mutation` 

There is any solution for it? I am not able to make it works

**Comment by B2o5T** [comment]
Please create a reproduction repo or take a look at various working examples in `examples` directory
