### ISSUE TITLE
Unable to set `schema` in a GraphQL Config file and `operations` in `parserOptions` 

### ISSUE THREAD

**Issue by jaydenseric** [B2o5T/graphql-eslint#1703]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Currently, if you have a project GraphQL config file, the ESLint plugin only looks at it and stops looking at the `parserOptions` ESLint config. This is a problem when the GraphQL config file only contains config for `schema`, but you need to set `parserOptions.operations` to a glob that selects JavaScript or TypeScript modules because your operations and fragments only exist as template strings with leading magic `/* GraphQL */` comments. It doesn't make sense to move that glob into the GraphQL config file, because tools other than the ESLint plugin that attempt to use the GraphQL config won't understand how to process GraphQL from JavaScript or TypeScript.

**To Reproduce** Steps to reproduce the behavior:

https://stackblitz.com/edit/github-jpjt8b?file=eslint.config.js&view=editor

If you run `npm run lint`, there is an ESLint error:

```
Oops! Something went wrong! :(

ESLint: 8.43.0

Error: Rule `known-fragment-names` requires `parserOptions.operations` to be set and loaded. See https://bit.ly/graphql-eslint-operations for more info
    at requireSiblingsOperations (<anonymous>)
    at handleMissingFragments (<anonymous>)
    at Document (<anonymous>)
    at ruleErrorHandler (<anonymous>)
    at emit (<anonymous>)
    at applySelector (<anonymous>)
    at applySelectors (<anonymous>)
    at enterNode (<anonymous>)
    at enterNode (<anonymous>)
    at <anonymous> (<anonymous>)
    at runRules (<anonymous>)
    at _verifyWithFlatConfigArrayAndWithoutProcessors (<anonymous>)
    at _verifyWithFlatConfigArrayAndProcessor (<anonymous>)
    at verify (<anonymous>)
    at verifyAndFix (<anonymous>)
    at verifyText (<anonymous>)
    at <anonymous> (<anonymous>)
```

If you delete the `.graphqlrc.json` file and try again, there is no error.

**Expected behavior**

The ESLint plugin should load from a project GraphQL config file as a base, then merge over the top any config that is in `parserOptions`; e.g. you may define `schema` in GraphQL config but then only define `operations` in `parserOptions`.

**Environment:**

- OS: macOS
- `@graphql-eslint/eslint-plugin`: v3.19.1
- Node.js: v20.3.1

**Additional context**

In our project, we want to use:

```
operations: "(components|helpers|hooks|pages)/**/*.{mts,ts,tsx}"
```

**Comment by B2o5T** [comment]
> The ESLint plugin should load from a project GraphQL config file as a base, then merge over the top any config that is in parserOptions; e.g. you may define schema in GraphQL config but then only define operations in parserOptions.

GraphQL-ESLint doesn't merge graphql-config with `parserOptions` (and there are no plans to merge it).

GraphQL-ESLint uses either physical config AND if config missing `parserOptions` setting. You can disable search physical config by specifying `skipGraphQLConfig: true`

if you want to use physical graphql-config, then you should specify your operations as `documents` key in `graphql-config`
