### ISSUE TITLE
Eslint with remote schema not working in runtime

### ISSUE THREAD

**Issue by Flashantik** [B2o5T/graphql-eslint#1721]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**
eslint not working in runtime with remote graphql schema 
(https://github.com/Flashantik/graphql-eslint/tree/remote)

<img width="822" alt="Screenshot 2023-07-01 at 01 01 37" src="https://github.com/B2o5T/graphql-eslint/assets/25429994/79690900-c377-46a2-9c0d-dfb8f3d7c8e1">

But `run lint `work fine:

<img width="914" alt="Screenshot 2023-07-01 at 01 14 02" src="https://github.com/B2o5T/graphql-eslint/assets/25429994/e59d6937-b3f2-4292-8cda-88c94ba03c18">

with local schema all works fine
(https://github.com/Flashantik/graphql-eslint/tree/local)
<img width="973" alt="Screenshot 2023-07-01 at 01 15 02" src="https://github.com/B2o5T/graphql-eslint/assets/25429994/a0917bfa-b3b6-40be-8dec-d399533323b5">

eslint with remote schema not working in runtime

**To Reproduce** Steps to reproduce the behavior:
1. git clone https://github.com/Flashantik/graphql-eslint/tree/remote 
2. npm i  

**Expected behavior**

eslint in runtime works 

**Environment:**

- OS: MacOs
- `@graphql-eslint/eslint-plugin`: 3.19.1
- Node.js: 18.13.0

**Additional context**
vscode 1.79.2 ( with "eslint.validate": ["graphql"] )  + eslint v2.4.2 (https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)

**Comment by B2o5T** [comment]
Since there are no problems in cli, problem goes from upstream vscode-eslint

**Comment by Flashantik** [comment]
> Since there are no problems in cli, problem goes from upstream vscode-eslint

Of course. But it is definitely related to graphql-eslint.

And even if I have to create an issue on vscode-eslint I would like to understand how a remote circuit affects this

**Comment by B2o5T** [comment]
@Flashantik 
I fixed the broken error message `Parsing error: Cannot read properties of undefined (reading '0')` in [`@graphql-eslint/eslint-plugin@3.19.3`](https://github.com/B2o5T/graphql-eslint/releases/tag/release-1688292639246)

Now you should have the correct error message 
<img width="839" alt="image" src="https://github.com/B2o5T/graphql-eslint/assets/7361780/780bf3f0-8335-4be0-8f7c-634e97c4aeb6">

that is produced due by https://github.com/B2o5T/graphql-eslint/issues/1091#issuecomment-1160952443 and https://github.com/microsoft/vscode-eslint/issues/1485

<img width="812" alt="image" src="https://github.com/B2o5T/graphql-eslint/assets/7361780/b8d5e12f-6634-4113-b36c-1908d68dd503">

And to fix it, add `.vscode/settings.json` file with the following content (node path you can get by `which node` in terminal)

```json
{
  "eslint.runtime": "/Users/dmytro/.nvm/versions/node/v18.16.1/bin/node"
}
```

now you should have working graphql-eslint with remote schema too 
<img width="779" alt="image" src="https://github.com/B2o5T/graphql-eslint/assets/7361780/3cb21f42-0f7f-4882-8036-c6b91af68497">

... tadaaam
