### ISSUE TITLE
Incompatible feature `Unexpected token '||='`

### ISSUE THREAD

**Issue by JounQin** [B2o5T/graphql-eslint#1747]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

https://github.com/prettier/eslint-plugin-prettier/actions/runs/5516930331/jobs/10058883702?pr=568

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

https://github.com/B2o5T/graphql-eslint/blob/28e99a2438bb5aa0f03d506158e4fb7ad435864c/packages/plugin/package.json#L8-L10

**To Reproduce** Steps to reproduce the behavior:

```log
/home/runner/work/eslint-plugin-prettier/eslint-plugin-prettier/node_modules/.pnpm/@graphql-eslint+eslint-plugin@3.20.0_graphql@16.7.1/node_modules/@graphql-eslint/eslint-plugin/cjs/parser.js:47
    options.documents ||= options.operations;
                      ^^^
```

**Expected behavior**

**Environment:**

- OS:
- `@graphql-eslint/eslint-plugin`: 3.20.0
- Node.js: v14

**Additional context**

**Comment by B2o5T** [comment]
Recently I switched to tsup, I’ll fix it once back from vacation
