### ISSUE TITLE
Provide a way to disable writing snapshots in `GraphQLRuleTester` 

### ISSUE THREAD

**Issue by wmartins** [B2o5T/graphql-eslint#1778]
**Is your feature request related to a problem? Please describe.**

I've written some custom rules with `GraphQLESLintRule` and I wrote some unit tests, following [this guide](https://the-guild.dev/graphql/eslint/docs/custom-rules#testing-your-rules), to validate my rule.

After running them (which I'm doing using Jest) I noticed that they're writing some snapshots, which is not exactly what I wanted.

**Describe the solution you'd like**

I don't have much context on the reasoning behind `GraphQLRuleTester`'s API, but one simple option would be having a way to configure this behavior, something like: `disableSnapshots` (which would be backwards compatible).

**Describe alternatives you've considered**

What I did here was basically copy `GraphQLRuleTester` from [testkit.ts](https://github.com/B2o5T/graphql-eslint/blob/a56ba32562e5450db8ccf58e371b08bc96cf2ffb/packages/plugin/src/testkit.ts) and remove the snapshot write part from it.

**Additional context**

N/A

**Comment by B2o5T** [comment]
You can use regular RuleTester from eslint

**Comment by wmartins** [comment]
Thank you @B2o5T! In fact we can use `RuleTester`, but you need to specify the `parser` and `parserOptions` correctly for it to work:

```ts
const ruleTester = new RuleTester({
  parser: require.resolve("@graphql-eslint/eslint-plugin"),
  parserOptions: {
    skipGraphQLConfig: true,
  },
})
```

I don't mind if we close this issue, but maybe one suggestion would be adding this info to the docs. Thanks again!

**Comment by B2o5T** [comment]
`GraphQLRuleTester` no longer will be bundled in v4, regular `RuleTester` or `FlatRuleTester` will be suggested instead
