### ISSUE TITLE
Allow deprecating input values

### ISSUE THREAD

**Issue by jhalborg** [B2o5T/graphql-eslint#1891]
**Describe the bug**

Using `@deprecated` on an input field throws the following error in this tool:

`error  Parsing error: [graphql-eslint] Error while loading schema: Directive "@deprecated" may not be used on ARGUMENT_DEFINITION`

The spec has merged the ability to deprecate input values in [this PR](https://github.com/graphql/graphql-spec/pull/805)

**To Reproduce** Steps to reproduce the behavior:

Add a `@deprecated` notice on an input field, i.e.

```
type Mutation {
  myMutation(firstParam: String @deprecated(reason: "Value taken from token instead"), secondParam: String!): String!
```

**Expected behavior**
A normal lint warning on the deprecated field

**Comment by B2o5T** [comment]
what version of graphql are you using?

**Comment by B2o5T** [comment]
Closing due silence, feel free to reply and I’ll reopen
