### ISSUE TITLE
Invoking from Node JS backend

### ISSUE THREAD

**Issue by gituserjava** [B2o5T/graphql-eslint#1901]
Can we invoke the parser from Node JS backend? If yes, can you please share some same code to invoke it? I tried to invoke `parseForESLint(code, options)` but I was unable to because I was not sure what to pass for `code` and the proper `options`. Please advise.

**Comment by B2o5T** [comment]
https://eslint.org/docs/latest/integrate/nodejs-api should help you, or please precise your question about what exactly you want to lint via node.js

**Comment by gituserjava** [comment]
Yes, this is working. Thank you!
