### ISSUE TITLE
Rule not found error

### ISSUE THREAD

**Issue by gituserjava** [B2o5T/graphql-eslint#1905]
I have configured ‘no-hashtag-description’ rule and when it validates the Graph ql schema, I get below error, can you please advise why I am getting this error?

Definition for rule ‘no-hashtag-description’ was not found. Why am I getting this?

**Comment by B2o5T** [comment]
use  `'@graphql-eslint/no-hashtag-description': 'error'` instead `'no-hashtag-description': 'error'`

**Comment by gituserjava** [comment]
This worked, thank you!
