### ISSUE TITLE
Custom error message or suggestion when `forbiddenSuffixes` is used on FieldDefinition

### ISSUE THREAD

**Issue by gituserjava** [B2o5T/graphql-eslint#1930]
Please provide an option to provide custom error message or suggestion when `forbiddenSuffixes` is used on FieldDefinition.

**Comment by B2o5T** [comment]
Please describe why you need it

**Comment by gituserjava** [comment]
Sure @B2o5T,

Imagine the correct field is `lastModifiedUser` and developer defines it incorrectly in the schema as `lastModifiedBy`, we want to provide error message to the developer that suffix`ModifiedBy` is incorrect and the correct suffix is `ModifiedUser`.

Currently error message is returned as `Field "lastModifiedBy" should not have "ModifiedBy" suffix` and I am looking for something like this `Field "lastModifiedBy" should not have "ModifiedBy" suffix and allowed suffix is "ModifiedUser"`. 

Please advise.

**Comment by B2o5T** [comment]
But you should still have 2 errors? 1st for forbidden prefix, 2nd for required

**Comment by gituserjava** [comment]
Why error message for required? The field `lastModifiedUser` can be optional. If the schema needs to define a field for last modified user then the developer need to define it as  `lastModifiedUser` and NOT `lastModifiedBy`

**Comment by B2o5T** [comment]
I thought you use `requiredPrefixes` too, anyway, I don’t think I want to add an option for a customizing error message, because if it starts with naming-convention, somebody wanted to customize another rule, and this will never end

**Comment by gituserjava** [comment]
Ok, the reason for asking is the current message conveys that a field should not have a particular suffix but it would be good if the current message can be returned to provide an alternate suffix that developer can use as a quick fix.

Anyways, thank you for quick turnaround.

**Comment by B2o5T** [comment]
After discussing with @dotansimha we decided to not add this option
