### ISSUE TITLE
@graphql-eslint/no-unreachable-types reports issues with graphql-modules

### ISSUE THREAD

**Issue by joshribakoff-sm** [B2o5T/graphql-eslint#956]
`common-schema.graphql`:

```gql
type MutationResult {}
```

`bar-schema.graphql`:

```gql
extend type mutation {
 go: MutationResult
}
```

**Actual results** - I get a lint error in `common-schema.graphql` saying the type is unused (which is technically "correct", if you just lint the one file standalone)

**Expected results** - It should see `MutationResult` is attached to the root (in the other file)

Notes - I guess this would entail loading all the schema and stitching in memory, and passing the stitched schema in the context when the lint rule runs? It's a shame it doesn't work, since identifying dead code is pretty useful, but the current behavior seems to preclude using the rule for user of `graphql-modules`

**Comment by B2o5T** [comment]
Hi @joshribakoff-sm!

1. Does both `common-schema.graphql` and `bar-schema.graphql` are included in your schema?
2. I see that you named your mutation as `mutation`. Do you have somewhere a schema definition? like
```gql
schema {
  mutation: mutation
}
```

**Comment by joshribakoff-sm** [comment]
Thanks so much for the reply, and sorry I don't have a reproduction repo :)

1 - Yes, both files are matched by this glob in the `.graphqlconfig`, `schema: apps/api/src/modules/*/*.graphql` and both files are being linted
2 - No I didn't have that line

Just now I tried deleting `node_modules` and re-installing, now the behavior is different. Superficially, it seems to be working as I expected. If I rename the `MutationResponse` to `ThisIsNotUsed`, it lights up red in my editor. When I run it on the CLI, I get this output (which is a bit confusing, I guess because the semantic error I introduced to test the rule breaks the parser)


```
 Error: Unknown type "MutationResponse". Did you mean "IMutationResponse", "MutationResponseo", "BrandResponse", "BrandsResponse", or "TeamResponse"?

Unknown type "MutationResponse". Did you mean "IMutationResponse", "MutationResponseo", "BrandResponse", "BrandsResponse", or "TeamResponse"?
Error while loading rule '@graphql-eslint/no-unreachable-types': Rule 'no-unreachable-types' requires 'parserOptions.schema' to be set and schema to be loaded. See http://bit.ly/graphql-eslint-schema for more info
Occurred while linting /Users/jribakoff/groundwater/apps/api/src/modules/common/common-schema.graphql
```

Sorry I opened this issue, I guess things were flaky but working 🤷
