### ISSUE TITLE
Can't load schema from URL

### ISSUE THREAD

**Issue by kaysond** [B2o5T/graphql-eslint#957]
**Describe the bug**

ESLint throws an error despite me having the options set correctly:
```
[Error - 3:35:15 PM] ESLint stack trace:
[Error - 3:35:15 PM] Error: Rule 'known-type-names' requires 'parserOptions.schema' to be set and schema to be loaded. See http://bit.ly/graphql-eslint-schema for more info
Occurred while linting C:\backup\QCSD\packages\client\src\components\SimulationDetails\DetailCardAnalyses\DetailCardAnalyses.graphql:1
Rule: "@graphql-eslint/known-type-names"
    at requireGraphQLSchemaFromContext (C:\backup\QCSD\node_modules\@graphql-eslint\eslint-plugin\index.js:192:15)
    at Document (C:\backup\QCSD\node_modules\@graphql-eslint\eslint-plugin\index.js:408:62)
    at ruleErrorHandler (C:\backup\QCSD\node_modules\eslint\lib\linter\linter.js:1107:28)
    at C:\backup\QCSD\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\backup\QCSD\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\backup\QCSD\node_modules\eslint\lib\linter\node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (C:\backup\QCSD\node_modules\eslint\lib\linter\node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (C:\backup\QCSD\node_modules\eslint\lib\linter\node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (C:\backup\QCSD\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:795:23)
```

`.eslintrc.json`
```
  "overrides": [
    {
      "files": ["*.graphql"],
      "rules": {
        "prettier/prettier": "error",
        "@graphql-eslint/known-type-names": "error"
      },
      "parser": "@graphql-eslint/eslint-plugin",
      "plugins": ["@graphql-eslint"],
      "parserOptions": {
        "operations": "./src/**/*.graphql",
        "schema": "http://localhost:4000/api"
      }
      //"extends": "plugin:@graphql-eslint/schema-recommended"
    }
  ]
```
(Things work fine if I comment out the `@graphql-eslint` rule.)

I can access the graphql api just fine in the browser, so I know it's running.

**Environment:**
- OS: Windows
- `@graphql-eslint/3.8.0`:
- NodeJS: 16.13.1
- Editor: VS Code 1.64.2

Is there a debug flag I can turn on for better logging? Not sure where things are failing

**Comment by B2o5T** [comment]
> Is there a debug flag I can turn on for better logging? Not sure where things are failing

Hi @kaysond, currently we don't have this feature, but we have a proposal https://github.com/dotansimha/graphql-eslint/issues/459. I'll try to add this in the next version

Currently, it's hard to say what is wrong with your setup, a reproduction repo will be helpful

**Comment by B2o5T** [comment]
Also, do you have a `graphqlconfig` in your project? If so add [this option](https://github.com/dotansimha/graphql-eslint/blob/master/docs/parser-options.md#skipgraphqlconfig)

**Comment by kaysond** [comment]
It seems this is a vscode issue, since I can run it from the command line with no issues!

**Comment by kaysond** [comment]
@B2o5T is there a way to log the result of the http request? This is necessary to debug the issue with extensions

**Comment by B2o5T** [comment]
hi @kaysond, I know only that `graphql-eslint` uses `@graphq-tools/url-loader` for loading graphql schema via URL endpoint. `url-loader` uses `sync-fetch` package for loading schema in sync mode. Try to debug `sync-fetch` package in `node_modules` folder.

In this place https://github.com/larsgw/sync-fetch/blob/main/index.js#L123 you should receive your response payload
