### ISSUE TITLE
Newest `@graphql-codegen/typescript-mongodb` breaks linting

### ISSUE THREAD

**Issue by tubbo** [B2o5T/graphql-eslint#960]
**Describe the bug**

Upgrading graphql codegen forced me to remove adding the `typescript-mongodb` directives as part of my schema:

```yaml
# this is my .graphqlrc.yml
schema:
  - api/src/http/graphql/third-party-scalars.js
  - api/src/http/graphql/types/**/*.gql
documents: web/src/**/*.gql
# ...
```

Originally, third-party-scalars looked like this:

```javascript
const { typeDefs } = require('graphql-scalars')
const { makeExecutableSchema } = require('@graphql-tools/schema')
const { DIRECTIVES } = require('@graphql-codegen/typescript-mongodb')
const { print } = require('graphql')

module.exports = makeExecutableSchema({
  typeDefs: [print(DIRECTIVES), ...typeDefs],
})
```

But, upgrading graphql-code-generator caused me to have to remove the `DIRECTIVES` portion, so it now looks like this:

```javascript
const { typeDefs } = require('graphql-scalars')
const { makeExecutableSchema } = require('@graphql-tools/schema')
const { print } = require('graphql')

module.exports = makeExecutableSchema({ typeDefs })
```

This broke graphql-eslint, which now complains:

```
error [graphql-eslint] Error while loading schema
 Error: Unknown directive "@entity".

Unknown directive "@id".

Unknown directive "@column".

Unknown directive "@column".

Unknown directive "@column".

Unknown directive "@column".

Unknown directive "@link".

Unknown directive "@link".

Unknown directive "@embedded".

[...]

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**

1. Try upgrading graphql-codegen while using graphql-eslint when using typescript-mongodb
2. This happens :(

**Expected behavior**

**Environment:**

- OS: macOS 12 / ubuntu-latest
- `"@graphql-eslint/eslint-plugin": "3.8.0"`
- NodeJS: v14

**Additional context**

n/a

**Comment by B2o5T** [comment]
Hi @tubbo, I took a look to docs of [`typescript-mongodb`](https://www.graphql-code-generator.com/plugins/typescript-mongodb#usage-example) and it steels says to import and add directives, does it’s outdated instruction?

**Comment by tubbo** [comment]
@B2o5T yeah it didn't mention anything needs to change, but if you keep it that way you get this lovely error in codegen...

```
  ✖ api/src/http/graphql/generated.ts
    Error: Unable to merge GraphQL directive "abstractEntity".
    Existing directive:
        directive @abstractEntity(discriminatorField: String!, additionalFields: [AdditionalEntityFields]) on INTERFACE
    Received directive:
        directive @abstractEntity(additionalFields: [AdditionalEntityFields], discriminatorField: String!) on INTERFACE
```

I'm really not sure what package is to blame here, sorry if this issue was not made in the right place.

**Comment by B2o5T** [comment]
Hi @tubbo, sorry for the long response, do you find a solution for your problem or maybe you still need help?

**Comment by dotansimha** [comment]
@tubbo I think you might need to add a custom schema for `graphql-eslint`, because it might not have the knowledge of those directives added in the codegen plugin.
