### ISSUE TITLE
`known-fragment-names` doesn't work with fragments in other files

### ISSUE THREAD

**Issue by tubbo** [B2o5T/graphql-eslint#977]
**Describe the bug**
[The documentation](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/known-fragment-names.md#correct-userfields-fragment-located-in-a-separate-file) describes a case for `known-fragment-names` wherein the fragment does not need to be defined in the same file as the query, but this is not true. Fragments defined in other files do not seem to be getting picked up by the plugin.

**To Reproduce**

Minimal reproduction of the issue: https://github.com/tubbo/graphql-eslint-repro

**Expected behavior**

The fragment should have been recognized as coming from its own file.

**Environment:**

- OS: macOS
- `@graphql-eslint/...`: 3.8.0
- NodeJS: 14

**Comment by B2o5T** [comment]
Hi, you have the wrong `parserOptions` setup.
```diff
"parserOptions": {
  "schema": "./schema.graphql",
- "operations": ["./query.graphql"]
+ "operations": ["./query.graphql", "fragment.graphql"]
}
```
