### ISSUE TITLE
Inconsistent validation of `known-fragment-names` with `union` type

### ISSUE THREAD

**Issue by aronwoost** [B2o5T/graphql-eslint#983]
**Describe the bug**

When using `known-fragment-names` on a `union` typed field, I get different results depending on if it's wrapped in another fragment or not.

**To Reproduce**

1. Checkout this repo: https://github.com/aronwoost/eslint-graphql-case
2. Run `npm run lint1`
3. Run `npm run lint2`

Result: `lint1` errors, `lint2` passes.

**Expected behavior**

Both commands should return the same results.

I'm actually not sure, if this usage of `union` is even "correct" GraphQL (we have it in the code base). 🧐🧐🧐

Regardless: both commands should behave the same.

**Comment by B2o5T** [comment]
Hi @aronwoost, thank you for your report and reproduction repo 👍!
I can confirm that there is a bug. This will be fixed on the next version of `graphql-eslint`.

**Comment by B2o5T** [comment]
fixed in [@graphql-eslint/eslint-plugin@3.9.1](https://github.com/B2o5T/graphql-eslint/releases/tag/%40graphql-eslint%2Feslint-plugin%403.9.1)

**Comment by aronwoost** [comment]
I can confirm that it works! 🎉 Thank you!
