### ISSUE TITLE
Surface underlying error messages if schema loading fails

### ISSUE THREAD

**Issue by joshribakoff-sm** [B2o5T/graphql-eslint#984]
**Is your feature request related to a problem? Please describe.**

```
directive @deprecated(
  reason: String = "No longer supported"
) on INPUT_FIELD_DEFINITION

input CreateUserRequest {
  first_name: String! @deprecated(msg: "foo")
}
```

Gives you a non descript error
![Screen Shot 2022-03-07 at 4 09 06 PM](https://user-images.githubusercontent.com/97546767/157139639-cb3b5fe5-0878-4c4e-9a55-2ccf0c539581.png)

**Describe the solution you'd like**
Surface the original error if the schema cannot be loaded:

```
/Users/jribakoff/a/node_modules/graphql/validation/validate.js:107
    throw new Error(errors.map(function (error) {
          ^
Error: Unknown argument "msg" on directive "@deprecated".
    at assertValidSDL (/Users/jribakoff/a/node_modules/graphql/validation/validate.js:107:11)
    at Object.buildASTSchema (/Users/jribakoff/a/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at makeExecutableSchema (/Users/jribakoff/a/node_modules/@graphql-tools/schema/index.js:495:26)
```

**Comment by B2o5T** [comment]
enhanced in [@graphql-eslint/eslint-plugin@3.10.0](https://github.com/B2o5T/graphql-eslint/releases/tag/%40graphql-eslint%2Feslint-plugin%403.10.0)

![image](https://user-images.githubusercontent.com/7361780/160512255-7f788f1b-3b2b-42d0-846a-c1abbd3e84c1.png)

![image](https://user-images.githubusercontent.com/7361780/160512275-c09695b2-f078-43f4-8465-06a5fbf5f5d0.png)
