### ISSUE TITLE
Watch schema files

### ISSUE THREAD

**Issue by joshribakoff-sm** [B2o5T/graphql-eslint#985]
**Is your feature request related to a problem? Please describe.**
I have to reload my editor window everytime I edit the schema. Eg.

```gql
query {
 me: User
}

type User {
  id: String!
}
```

now edit to this:
```gql
query {
 me: User2
}

type User2 {
  id: String!
}
```

Gives: 

> Type "User2" is unreachableeslint[@graphql-eslint/no-unreachable-types](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/no-unreachable-types.md)

Once the user reloads vscode, eslint restarts and your plugin rereads the schema and the stale error is fixed. This is annoying.

**Describe the solution you'd like**
If eslint is running in watch mode, watch the underlying schema files and reload them. Reload the schema files every-time the rule in invoked if necessary.

**Comment by B2o5T** [comment]
duplicate https://github.com/B2o5T/graphql-eslint/issues/593
