### ISSUE TITLE
parserOptions.schema error for require-id-when-available rule

### ISSUE THREAD

**Issue by sujithgowda** [B2o5T/graphql-eslint#987]
**Describe the bug**
Trying to validate queries in apollo client under gql tag results in  following error
Error while loading rule '@graphql-eslint/require-id-when-available': Rule 'require-id-when-available' requires 'parserOptions.schema' to be set and schema to be loaded

use the following eslintrc.json file

`{
  "root": true,
  "ignorePatterns": ["**/*"],
  "plugins": ["@nrwl/nx"],
  "overrides": [
    { 
      "files": ["*.ts"],
      "processor": "@graphql-eslint/graphql"
  },
    {
      "files": [
        "*.ts"
      ],
      "parser": "@graphql-eslint/eslint-plugin",      
      "parserOptions": {        
        "schema": "./apps/customer-api-federated/src/profile.graphql"
      },
      "plugins": [
        "@graphql-eslint"
      ],      
        "rules": {
          "@graphql-eslint/require-id-when-available": "error",
          "@graphql-eslint/no-anonymous-operations": "error"
        }        
      }
  ]
}
`

**Environment:**

- OS: windows
- `@graphql-eslint/...`:3.9.0
- NodeJS: 14.16.1

**Comment by B2o5T** [comment]
Hi @sujithgowda, to help you I need a reproduction repo or some debug information of your configuration.

Please install `@graphql-eslint/eslint-plugin@3.9.1-alpha-ebcc06f.0` alpha version that includes debugging printing.
After installation run `DEBUG=graphql-eslint:* eslint .` and show your output.

**Comment by B2o5T** [comment]
I close this issue as I didn't receive a response
