### ISSUE TITLE
Doesn't do anything in a Next + Relay project

### ISSUE THREAD

**Issue by n3ps** [B2o5T/graphql-eslint#988]
**Describe the bug**
Doesn't seem to do anything. I am expecting it to show warnings or errors.

**To Reproduce**
- Follow the instructions in the README
- yarn add -D @graphql-eslint/eslint-plugin
- update the plugins list
```
"plugins": [..., "@typescript-eslint", "@graphql-eslint"],
```

- add the overrides section

```
"overrides": [
    {
      "files": ["*.tsx"],
      "processor": "@graphql-eslint/graphql"
    },
    {
      "files": ["*.graphql"],
      "extends": "plugin:@graphql-eslint/schema-recommended"
    }
  ]
```

**Expected behavior**
Expect lint rules to be processed

**Environment:**

- OS: Big Sur
- `@graphql-eslint/eslint-plugin": "^3.9.0"`:
- NodeJS: 16.14

**Additional context**
Next.js v12 + React Relay v13 project

**Comment by B2o5T** [comment]
Hi @n3ps, to help you I need a reproduction repo or some debug information of your configuration.

Please install `@graphql-eslint/eslint-plugin@3.9.1-alpha-ebcc06f.0` alpha version that includes debugging printing.
After installation run `DEBUG=graphql-eslint:* eslint .` and show your output.

**Comment by n3ps** [comment]
@B2o5T I tried the above and the output is quite large but I do see the lint working and you made a good point. It worked using vanillla `eslint` and I was using `next lint` which seems to ignore this specific plugin.

**Comment by PatrykWalach** [comment]
`next lint` seems to ignore `"overrides"` in general
