### ISSUE TITLE
eslint cache does not get invalidated when `.graphqlconfig` is changed

### ISSUE THREAD

**Issue by aronwoost** [B2o5T/graphql-eslint#993]
**Describe the bug**
eslint cache does not get invalidated when `.graphqlconfig` is changed.

**To Reproduce**

Check this repo: https://github.com/aronwoost/graphql-eslint-cache-invalidation
How to reproduce: https://github.com/aronwoost/graphql-eslint-cache-invalidation/blob/master/README.md

**Expected behavior**
eslint cache should get invalidated when `.graphqlconfig` changes. Ideally only for `*.graphql` files.

**Comment by B2o5T** [comment]
Hi @aronwoost, thanks for the report and reproduction.
I was able to reproduce, but unfortunately I don't have an idea how this can be fixed 🤷‍♂️

**Comment by aronwoost** [comment]
😁 This is fine, I guess. Not sure how `eslint` is doing the hole cache invalidation.

Anyway, feel free to close this ticket. At least it's here for reference.

Workaround: make sure you also do a change to `.eslintrc` to invalidate the cache (can also only be adding a comment).

**Comment by aronwoost** [comment]
For reference: https://github.com/eslint/eslint/issues/12578

**Comment by B2o5T** [comment]
@aronwoost thanks for the reference, seems like currently this can't be fixed, so I close this issue for now
